# Generated by Django 5.2.9 on 2026-01-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objednavky', '0018_pricerecalculationlog_pricerecalculationdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricerecalculationdetail',
            options={'verbose_name': 'Přepočet cen detail', 'verbose_name_plural': 'Přepočet cen detail'},
        ),
        migrations.AlterModelOptions(
            name='pricerecalculationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Přepočet cen log', 'verbose_name_plural': 'Přepočet cen log'},
        ),
    ]
