# Generated by Django 5.2.9 on 2026-04-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jidelnicek', '0008_jidlo_sk_bezmasy_pokrm_jidlo_sk_bile_maso_and_more'),
        ('objednavky', '0019_alter_pricerecalculationdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'menu_item')},
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['vydano', 'datum_vydani'], name='objednavky__vydano_1af385_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'menu_item'], name='objednavky__order_i_1847f8_idx'),
        ),
    ]
