# Generated by Django 5.2.9 on 2026-04-27 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objednavky', '0021_ordercancellationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'datum_vydeje'], name='objednavky__user_id_dcaac4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['datum_vydeje', 'status'], name='objednavky__datum_v_a3ffa6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status', 'datum_vydeje'], name='objednavky__user_id_f48b80_idx'),
        ),
    ]
