# Generated by Django 5.2.9 on 2026-03-10 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0005_alter_customuser_identifikacni_medium'),
    ]

    operations = [
        migrations.CreateModel(
            name='StravovaciSkupina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(help_text='Např. SS, ZS1, ZS2…', max_length=20, unique=True, verbose_name='Kód skupiny')),
                ('nazev', models.CharField(help_text="Např. 'Střední škola – žáci'.", max_length=100, verbose_name='Název skupiny')),
                ('typ_vzdelavani', models.CharField(choices=[('MS', 'Mateřská škola'), ('ZS1', 'ZŠ 7–10 let'), ('ZS2', 'ZŠ 11–14 let'), ('SS', 'Střední škola'), ('JINE', 'Jiné')], default='SS', max_length=10, verbose_name='Typ vzdělávání')),
                ('django_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stravovaci_skupina', to='auth.group', verbose_name='Django skupina (pro dotace, oprávnění)')),
            ],
            options={
                'verbose_name': 'Stravovací skupina',
                'verbose_name_plural': 'Stravovací skupiny',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='stravovaci_skupina',
            field=models.ForeignKey(blank=True, help_text='Např. SŠ žák, ZŠ 1. stupeň…', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.stravovaciskupina', verbose_name='Stravovací skupina'),
        ),
    ]
