# Generated by Django 5.2.9 on 2026-04-20 08:23

from django.db import migrations, models


def oznac_platby_uctu(apps, schema_editor):
    Vklad = apps.get_model("users", "Vklad")
    PokladniDoklad = apps.get_model("pokladna", "PokladniDoklad")
    pohyb_ids = PokladniDoklad.objects.filter(
        typ_dokladu="PRODEJ",
        zpusob_platby="KONTO",
        konto_pohyb_id__isnull=False,
    ).values_list("konto_pohyb_id", flat=True)
    Vklad.objects.filter(id__in=pohyb_ids, castka__lt=0).update(status="platba_uctu")


def vrat_platby_uctu_na_standard(apps, schema_editor):
    Vklad = apps.get_model("users", "Vklad")
    Vklad.objects.filter(status="platba_uctu").update(status="standard")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_vklad_pokladna'),
        ('pokladna', '0009_alter_pokladna_hotovostni_zustatek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vklad',
            name='status',
            field=models.CharField(choices=[('standard', 'Standardní vklad'), ('nulovani_konta', 'Nulování konta'), ('platba_uctu', 'Platba účtu z konta')], default='standard', editable=False, max_length=32),
        ),
        migrations.RunPython(oznac_platby_uctu, vrat_platby_uctu_na_standard),
    ]
