# Generated by Django 5.2.9 on 2026-04-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_vklad_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Při dalším přihlášení bude uživatel povinně vyzván ke změně hesla.', verbose_name='Vyžadovat změnu hesla'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Heslo změněno'),
        ),
    ]
