# Generated by Django 5.2.9 on 2026-05-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_force_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='identifikacni_medium_mobil',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ISIC mobil'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='identifikacni_medium',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ISIC karta'),
        ),
    ]
