# Generated by Django 5.2.9 on 2026-04-19 16:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_default_questions(apps, schema_editor):
    AnketniOtazka = apps.get_model('ankety', 'AnketniOtazka')
    defaults = [
        (10, "Jak ti jídlo chutnalo?", "1 = vůbec, 5 = výborně"),
        (20, "Jak hodnotíš vzhled a servírování jídla?", "1 = velmi špatné, 5 = velmi dobré"),
        (30, "Byla porce dostatečná?", "1 = nedostatečná, 5 = ideální"),
    ]
    for poradi, text, napoveda in defaults:
        AnketniOtazka.objects.get_or_create(
            text=text,
            defaults={"poradi": poradi, "napoveda": napoveda, "aktivni": True, "povinna": True},
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objednavky', '0019_alter_pricerecalculationdetail_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnketniOtazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Text otázky')),
                ('napoveda', models.CharField(blank=True, max_length=255, verbose_name='Nápověda')),
                ('aktivni', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('povinna', models.BooleanField(default=True, verbose_name='Povinná')),
                ('poradi', models.PositiveIntegerField(default=10, verbose_name='Pořadí')),
            ],
            options={
                'verbose_name': 'Anketní otázka',
                'verbose_name_plural': 'Anketní otázky',
                'ordering': ('poradi', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HodnoceniJidla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_vydeje', models.DateField(verbose_name='Datum výdeje')),
                ('jidlo_nazev', models.CharField(max_length=255, verbose_name='Jídlo')),
                ('poznamka', models.TextField(blank=True, verbose_name='Poznámka strávníka')),
                ('vytvoreno', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vyplněno')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hodnoceni', to='objednavky.orderitem', verbose_name='Vydaná položka objednávky')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hodnoceni_jidel', to=settings.AUTH_USER_MODEL, verbose_name='Strávník')),
            ],
            options={
                'verbose_name': 'Hodnocení jídla',
                'verbose_name_plural': 'Hodnocení jídel',
                'ordering': ('-vytvoreno',),
            },
        ),
        migrations.CreateModel(
            name='OdpovedHodnoceni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znamka', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Hodnocení 1-5')),
                ('hodnoceni_jidla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odpovedi', to='ankety.hodnocenijidla', verbose_name='Hodnocení')),
                ('otazka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odpovedi', to='ankety.anketniotazka', verbose_name='Otázka')),
            ],
            options={
                'verbose_name': 'Odpověď hodnocení',
                'verbose_name_plural': 'Odpovědi hodnocení',
                'ordering': ('otazka__poradi', 'otazka_id'),
                'unique_together': {('hodnoceni_jidla', 'otazka')},
            },
        ),
        migrations.RunPython(seed_default_questions, migrations.RunPython.noop),
    ]
