# Generated by Django 5.2.9 on 2026-04-27 16:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankety', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MesicniAnketa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=255, verbose_name='Název hlasování')),
                ('popis', models.TextField(blank=True, verbose_name='Popis')),
                ('rok', models.PositiveSmallIntegerField(verbose_name='Rok')),
                ('mesic', models.PositiveSmallIntegerField(choices=[(1, 'Leden'), (2, 'Únor'), (3, 'Březen'), (4, 'Duben'), (5, 'Květen'), (6, 'Červen'), (7, 'Červenec'), (8, 'Srpen'), (9, 'Září'), (10, 'Říjen'), (11, 'Listopad'), (12, 'Prosinec')], verbose_name='Měsíc')),
                ('navrhujici_trida', models.CharField(blank=True, max_length=120, verbose_name='Navrhující třída')),
                ('hlasovani_od', models.DateField(verbose_name='Hlasování od')),
                ('hlasovani_do', models.DateField(verbose_name='Hlasování do')),
                ('aktivni', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('vytvoreno', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vytvořeno')),
            ],
            options={
                'verbose_name': 'Měsíční anketa menu',
                'verbose_name_plural': 'Měsíční ankety menu',
                'ordering': ('-rok', '-mesic', '-vytvoreno'),
                'constraints': [models.UniqueConstraint(fields=('rok', 'mesic'), name='ankety_mesicnianketa_unique_obdobi')],
            },
        ),
        migrations.CreateModel(
            name='MesicniAnketaVarianta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=255, verbose_name='Název varianty')),
                ('popis', models.TextField(blank=True, verbose_name='Popis varianty')),
                ('poradi', models.PositiveIntegerField(default=10, verbose_name='Pořadí')),
                ('anketa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varianty', to='ankety.mesicnianketa', verbose_name='Měsíční anketa')),
            ],
            options={
                'verbose_name': 'Varianta měsíční ankety',
                'verbose_name_plural': 'Varianty měsíční ankety',
                'ordering': ('poradi', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MesicniAnketaHlas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hlasovano', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hlasováno')),
                ('anketa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hlasy', to='ankety.mesicnianketa', verbose_name='Měsíční anketa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anketni_hlasy', to=settings.AUTH_USER_MODEL, verbose_name='Strávník')),
                ('varianta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hlasy', to='ankety.mesicnianketavarianta', verbose_name='Zvolená varianta')),
            ],
            options={
                'verbose_name': 'Hlas v měsíční anketě',
                'verbose_name_plural': 'Hlasy v měsíční anketě',
                'ordering': ('-hlasovano',),
                'constraints': [models.UniqueConstraint(fields=('anketa', 'user'), name='ankety_mesicnianketahlas_unique_anketa_user')],
            },
        ),
    ]
