ADMIN_VIEW_AREAS = (
    {
        "slug": "admin-dashboard",
        "name": "Admin přehled",
        "description": "Provozní přehled, ruční úlohy, health-checky a správa modulů.",
        "app_labels": ["admin_dashboard"],
        "route_prefixes": ["/admin/admin_dashboard/"],
    },
    {
        "slug": "users-admin",
        "name": "Uživatelé",
        "description": "Správa uživatelů, skupin, vkladů a kont.",
        "app_labels": ["users"],
        "route_prefixes": ["/admin/users/customuser/", "/admin/users/vklad/"],
    },
    {
        "slug": "user-groups-admin",
        "name": "Stravovací skupiny a nulování kont",
        "description": "Pokročilé zásahy do stravovacích skupin a ruční nulování kont.",
        "app_labels": [],
        "route_prefixes": ["/admin/users/stravovaciskupina/", "/admin/users/vklad/nulovani-konta/"],
    },
    {
        "slug": "auth-admin",
        "name": "Autentizace a autorizace",
        "description": "Django skupiny a technická správa oprávnění.",
        "app_labels": ["auth"],
        "route_prefixes": ["/admin/auth/"],
    },
    {
        "slug": "menu-admin",
        "name": "Jídelníček",
        "description": "Druhy jídel, katalog jídel a tvorba jídelníčků.",
        "app_labels": ["jidelnicek"],
        "route_prefixes": ["/admin/jidelnicek/"],
    },
    {
        "slug": "orders-admin",
        "name": "Objednávky",
        "description": "Objednávky, bulk operace a přepočty cen.",
        "app_labels": ["objednavky"],
        "route_prefixes": ["/admin/objednavky/"],
    },
    {
        "slug": "issuance-admin",
        "name": "Výdej",
        "description": "Výdej jídel, kuchyňský přehled a vydané účtenky.",
        "app_labels": ["vydej", "vydej_jidel", "vydej_frontend"],
        "route_prefixes": ["/admin/vydej/", "/admin/vydej_jidel/"],
    },
    {
        "slug": "canteen-operations-admin",
        "name": "Provoz jídelny",
        "description": "Provozní dashboard obsluhy, živý výdej a operativní rozcestník jídelny.",
        "app_labels": ["provoz_jidelny"],
        "route_prefixes": ["/admin/provoz_jidelny/"],
    },
    {
        "slug": "subsidy-admin",
        "name": "Dotace",
        "description": "Dotace a skupinová provozní pravidla.",
        "app_labels": ["dotace"],
        "route_prefixes": ["/admin/dotace/"],
    },
    {
        "slug": "canteen-settings-admin",
        "name": "Nastavení jídelny",
        "description": "Globální nastavení jídelny, uzávěrky a provozní časy.",
        "app_labels": ["canteen_settings"],
        "route_prefixes": ["/admin/canteen_settings/"],
    },
    {
        "slug": "reports-admin",
        "name": "Reporty",
        "description": "Provozní a manažerské reporty jídelny.",
        "app_labels": ["reporty"],
        "route_prefixes": ["/admin/reporty/"],
    },
    {
        "slug": "finance-admin",
        "name": "Finance",
        "description": "Finanční dashboardy a účetní přehledy.",
        "app_labels": ["finance"],
        "route_prefixes": ["/admin/finance/"],
    },
    {
        "slug": "pricing-admin",
        "name": "Přepočty cen",
        "description": "Přepočty cen, jejich historie a detailní audit změn.",
        "app_labels": ["prepocty"],
        "route_prefixes": ["/admin/prepocty/"],
    },
    {
        "slug": "warehouse-admin",
        "name": "Sklad",
        "description": "Skladové hospodářství, inventury a spotřební koš.",
        "app_labels": ["sklad"],
        "route_prefixes": ["/admin/sklad/"],
    },
    {
        "slug": "cashdesk-admin",
        "name": "Pokladna",
        "description": "Pokladna, uzávěrky a pokladní provoz.",
        "app_labels": ["pokladna"],
        "route_prefixes": ["/admin/pokladna/", "/pokladna/"],
    },
    {
        "slug": "surveys-admin",
        "name": "Ankety",
        "description": "Hodnocení jídel a ankety.",
        "app_labels": ["ankety"],
        "route_prefixes": ["/admin/ankety/", "/ankety/"],
    },
    {
        "slug": "billing-admin",
        "name": "Fakturace",
        "description": "Fakturační dávky a přehledy pro účetní procesy.",
        "app_labels": ["fakturace"],
        "route_prefixes": ["/admin/fakturace/"],
    },
    {
        "slug": "licensing-admin",
        "name": "Licencování",
        "description": "Správa licence aplikace, ověření platnosti a licenční audit.",
        "app_labels": ["licencovani"],
        "route_prefixes": ["/admin/licencovani/"],
    },
)
