ADMIN_VIEW_AREAS = (
    {
        "slug": "admin-dashboard",
        "name": "Admin dashboard",
        "description": "Provozní přehled, ruční úlohy, health-checky a správa modulů.",
        "app_labels": ["admin_dashboard"],
        "route_prefixes": ["/admin/admin_dashboard/"],
    },
    {
        "slug": "users-admin",
        "name": "Uživatelé",
        "description": "Správa uživatelů, skupin, vkladů a kont.",
        "app_labels": ["users", "auth"],
        "route_prefixes": ["/admin/users/", "/admin/auth/"],
    },
    {
        "slug": "menu-admin",
        "name": "Jídelníček",
        "description": "Druhy jídel, katalog jídel a tvorba jídelníčků.",
        "app_labels": ["jidelnicek"],
        "route_prefixes": ["/admin/jidelnicek/"],
    },
    {
        "slug": "orders-admin",
        "name": "Objednávky",
        "description": "Objednávky, bulk operace a přepočty cen.",
        "app_labels": ["objednavky"],
        "route_prefixes": ["/admin/objednavky/"],
    },
    {
        "slug": "issuance-admin",
        "name": "Výdej",
        "description": "Výdej jídel, kuchyňský přehled a výdejní konfigurace.",
        "app_labels": ["vydej", "vydej_jidel", "vydej_frontend"],
        "route_prefixes": ["/admin/vydej/", "/admin/vydej_jidel/"],
    },
    {
        "slug": "subsidy-admin",
        "name": "Dotace",
        "description": "Dotace a skupinová provozní pravidla.",
        "app_labels": ["dotace"],
        "route_prefixes": ["/admin/dotace/"],
    },
    {
        "slug": "canteen-settings-admin",
        "name": "Nastavení jídelny",
        "description": "Globální nastavení jídelny, uzávěrky a provozní časy.",
        "app_labels": ["canteen_settings"],
        "route_prefixes": ["/admin/canteen_settings/"],
    },
    {
        "slug": "reports-admin",
        "name": "Reporty a finance",
        "description": "Reporty, finance a přepočtové dashboardy.",
        "app_labels": ["reporty", "finance", "prepocty"],
        "route_prefixes": ["/admin/reporty/", "/admin/finance/", "/admin/prepocty/"],
    },
    {
        "slug": "warehouse-admin",
        "name": "Sklad",
        "description": "Skladové hospodářství, inventury a spotřební koš.",
        "app_labels": ["sklad"],
        "route_prefixes": ["/admin/sklad/"],
    },
    {
        "slug": "cashdesk-admin",
        "name": "Pokladna",
        "description": "Pokladna, uzávěrky a pokladní provoz.",
        "app_labels": ["pokladna"],
        "route_prefixes": ["/admin/pokladna/", "/pokladna/"],
    },
    {
        "slug": "surveys-admin",
        "name": "Ankety",
        "description": "Hodnocení jídel a ankety.",
        "app_labels": ["ankety"],
        "route_prefixes": ["/admin/ankety/", "/ankety/"],
    },
    {
        "slug": "billing-admin",
        "name": "Fakturace",
        "description": "Fakturační dávky a přehledy pro účetní procesy.",
        "app_labels": ["fakturace"],
        "route_prefixes": ["/admin/fakturace/"],
    },
)
