OPERATIONAL_ADMIN_ROLES = [
    {
        "slug": "vedouci-jidelny",
        "name": "Vedoucí jídelny",
        "description": "Hlavní provozní role pro vedení jídelny a správu každodenního provozu.",
        "best_for": "Dej ji člověku, který řídí provoz jídelny a potřebuje řešit většinu agendy bez zásahu vývojáře.",
        "scope_note": "Může nastavovat provoz, uživatele, jídelníček, objednávky, výdej i dotace. Finance a sklad má silně, ale ne jako čistě účetní nebo skladovou specializaci.",
        "assignments": {
            "admin-dashboard": "control",
            "users-admin": "control",
            "menu-admin": "control",
            "orders-admin": "control",
            "issuance-admin": "control",
            "canteen-operations-admin": "control",
            "subsidy-admin": "control",
            "canteen-settings-admin": "control",
            "reports-admin": "control",
            "finance-admin": "write",
            "pricing-admin": "write",
            "cashdesk-admin": "write",
            "warehouse-admin": "write",
            "surveys-admin": "control",
            "billing-admin": "view",
            "licensing-admin": "view",
        },
    },
    {
        "slug": "jidelnicek-a-objednavky",
        "name": "Jídelníček a objednávky",
        "description": "Samostatná role pro tvorbu jídelníčku, správu objednávek a návazné provozní úpravy.",
        "best_for": "Dej ji pracovníkovi, který skládá menu, hlídá objednávky a řeší denní operativu kolem stravy.",
        "scope_note": "Nemá řídit uživatele, dotace ani globální nastavení jídelny. Je zaměřená na obsah jídelníčku a objednávkový provoz.",
        "assignments": {
            "menu-admin": "control",
            "orders-admin": "control",
            "issuance-admin": "view",
            "canteen-operations-admin": "view",
            "reports-admin": "view",
            "surveys-admin": "view",
        },
    },
    {
        "slug": "vydej-jidel",
        "name": "Výdej jídel",
        "description": "Obsluha výdeje s přístupem k frontě, objednávkám a dennímu jídelníčku.",
        "best_for": "Dej ji obsluze výdeje, která potřebuje vidět dnešní menu a pracovat s vydáváním jídel.",
        "scope_note": "Není určená pro úpravy systému, financí ani skladových dat. Má hlavně operativní kontrolu nad výdejem.",
        "assignments": {
            "menu-admin": "view",
            "orders-admin": "view",
            "issuance-admin": "control",
            "canteen-operations-admin": "control",
        },
    },
    {
        "slug": "pokladni",
        "name": "Pokladní",
        "description": "Pokladní provoz, práce se zůstatky a přehled nad uživatelskými účty.",
        "best_for": "Dej ji člověku, který vybírá platby, řeší zůstatky a potřebuje pracovat s kontem strávníků.",
        "scope_note": "Nemá plně spravovat jídelníček ani sklad. Vidí potřebné souvislosti, ale hlavní doménou je pokladna a konto uživatelů.",
        "assignments": {
            "users-admin": "write",
            "orders-admin": "view",
            "cashdesk-admin": "control",
            "reports-admin": "view",
            "finance-admin": "view",
        },
    },
    {
        "slug": "skladnik",
        "name": "Skladník",
        "description": "Role zaměřená na skladové hospodářství, inventury a kontrolní přehledy.",
        "best_for": "Dej ji pracovníkovi skladu, který řeší příjemky, pohyby, inventury a kontrolní výstupy.",
        "scope_note": "Není určená pro objednávky, pokladnu ani uživatelskou administraci. Má se držet skladu a souvisejících přehledů.",
        "assignments": {
            "menu-admin": "view",
            "warehouse-admin": "control",
            "reports-admin": "view",
        },
    },
    {
        "slug": "ekonom-ucetni",
        "name": "Ekonom / účetní",
        "description": "Finanční dohled, reporty a fakturační agenda bez zásahu do operativního provozu.",
        "best_for": "Dej ji ekonomce nebo účetní, která potřebuje reporty, fakturaci a finanční přehled nad provozem.",
        "scope_note": "Nemá řídit denní výdej ani skládat jídelníček. Je určená spíš pro dohled, vyúčtování a kontrolu financí.",
        "assignments": {
            "users-admin": "view",
            "orders-admin": "view",
            "reports-admin": "control",
            "finance-admin": "control",
            "pricing-admin": "control",
            "billing-admin": "control",
            "cashdesk-admin": "view",
            "licensing-admin": "view",
        },
    },
    {
        "slug": "auditor",
        "name": "Auditor / dohled",
        "description": "Čistě čtecí role pro kontrolu dat, audit a dohled nad provozem.",
        "best_for": "Dej ji tam, kde chceš bezpečný dohled bez rizika nechtěných změn.",
        "scope_note": "Všechno vidí, ale nikde by neměla nic měnit. Hodí se pro vedení školy, kontrolu nebo externí audit.",
        "assignments": {
            "users-admin": "view",
            "menu-admin": "view",
            "orders-admin": "view",
            "issuance-admin": "view",
            "canteen-operations-admin": "view",
            "subsidy-admin": "view",
            "canteen-settings-admin": "view",
            "reports-admin": "view",
            "finance-admin": "view",
            "pricing-admin": "view",
            "warehouse-admin": "view",
            "cashdesk-admin": "view",
            "surveys-admin": "view",
            "billing-admin": "view",
            "licensing-admin": "view",
        },
    },
]
