# Generated by Django 5.2.9 on 2026-04-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancniDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Finanční dashboard',
                'verbose_name_plural': 'Finanční dashboard',
                'managed': False,
            },
        ),
    ]
