# Generated by Django 5.2.9 on 2026-01-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vydej', '0004_stornovaneobjednavky'),
    ]

    operations = [
        migrations.CreateModel(
            name='VydejSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout_seconds', models.PositiveIntegerField(default=20, help_text='Po kolika sekundách od nalezení objednávky se automaticky vydá.', verbose_name='Timeout výdeje (sekundy)')),
            ],
            options={
                'verbose_name': 'Nastavení výdeje',
                'verbose_name_plural': 'Nastavení výdeje',
            },
        ),
    ]
