# Generated by Django 5.2.9 on 2026-04-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vydej', '0005_vydejsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stornovaneobjednavky',
            options={'verbose_name': 'Stornovaná objednávka', 'verbose_name_plural': 'Stornované objednávky'},
        ),
    ]
