# Generated by Django 5.2.9 on 2026-01-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vydej_jidel', '0002_vydejsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vydejsettings',
            name='timeout_seconds',
            field=models.IntegerField(default=30),
        ),
    ]
