# Generated by Django 5.2.9 on 2026-01-21 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jidelnicek', '0003_remove_jidelnicek_jidla_polozkajidelnicku_druh_jidla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surovina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, unique=True, verbose_name='Název suroviny')),
                ('jednotka', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Litr'), ('ks', 'Kus')], max_length=10, verbose_name='Jednotka')),
            ],
            options={
                'verbose_name': 'Surovina',
                'verbose_name_plural': 'Suroviny',
            },
        ),
        migrations.CreateModel(
            name='StavSkladu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Množství na skladě')),
                ('min_mnozstvi', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Minimální množství (pro upozornění)')),
                ('surovina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stav', to='sklad.surovina')),
            ],
            options={
                'verbose_name': 'Stav skladu',
                'verbose_name_plural': 'Stavy skladu',
            },
        ),
        migrations.CreateModel(
            name='RecepturaPolozka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi_na_porci', models.DecimalField(decimal_places=3, help_text='Ve stejné jednotce jako surovina (kg, l, ks).', max_digits=10, verbose_name='Množství na 1 porci')),
                ('jidlo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptura', to='jidelnicek.jidlo')),
                ('surovina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='v_receptech', to='sklad.surovina')),
            ],
            options={
                'verbose_name': 'Položka receptury',
                'verbose_name_plural': 'Položky receptur',
                'unique_together': {('jidlo', 'surovina')},
            },
        ),
    ]
