# Generated by Django 5.2.9 on 2026-01-21 17:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkladDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Skladový dashboard',
                'verbose_name_plural': 'Skladový dashboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrijemSkladu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum příjmu')),
                ('popis', models.CharField(blank=True, max_length=255, verbose_name='Poznámka')),
                ('uzavreny', models.BooleanField(default=False, verbose_name='Uzavřený (převod do skladu)')),
                ('vytvoril', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
            ],
            options={
                'verbose_name': 'Příjem na sklad',
                'verbose_name_plural': 'Příjmy na sklad',
            },
        ),
        migrations.CreateModel(
            name='PoložkaPrijmu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi', models.DecimalField(decimal_places=3, help_text='Ve stejné jednotce jako surovina.', max_digits=10, verbose_name='Množství')),
                ('surovina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.surovina', verbose_name='Surovina')),
                ('prijem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='sklad.prijemskladu', verbose_name='Příjem')),
            ],
            options={
                'verbose_name': 'Položka příjmu',
                'verbose_name_plural': 'Položky příjmu',
            },
        ),
    ]
