# Generated by Django 5.2.9 on 2026-01-21 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0002_skladdashboard_prijemskladu_položkaprijmu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoložkaPrijmu',
            new_name='PolozkaPrijmu',
        ),
        migrations.CreateModel(
            name='Inventura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum inventury')),
                ('popis', models.CharField(blank=True, max_length=255, verbose_name='Poznámka')),
                ('uzavrena', models.BooleanField(default=False, verbose_name='Uzavřená (promítnuto do skladu)')),
                ('vytvoril', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
            ],
            options={
                'verbose_name': 'Inventura',
                'verbose_name_plural': 'Inventury',
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='PolozkaInventury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stav_pred', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Stav před')),
                ('fyzicky_stav', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Fyzický stav')),
                ('rozdil', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Rozdíl')),
                ('inventura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='sklad.inventura', verbose_name='Inventura')),
                ('surovina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.surovina', verbose_name='Surovina')),
            ],
            options={
                'verbose_name': 'Položka inventury',
                'verbose_name_plural': 'Položky inventury',
                'unique_together': {('inventura', 'surovina')},
            },
        ),
    ]
