# Generated by Django 5.2.9 on 2026-01-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0003_rename_položkaprijmu_polozkaprijmu_inventura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polozkainventury',
            name='rozdil',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Rozdíl'),
        ),
        migrations.AlterField(
            model_name='polozkainventury',
            name='stav_pred',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Stav před'),
        ),
    ]
