# Generated by Django 5.2.9 on 2026-01-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0004_alter_polozkainventury_rozdil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventurniDoklad',
            fields=[
            ],
            options={
                'verbose_name': 'Inventurní doklad',
                'verbose_name_plural': 'Inventurní doklady',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sklad.inventura',),
        ),
    ]
