# Generated by Django 5.2.9 on 2026-03-09 19:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jidelnicek', '0007_jidlo_foto'),
        ('sklad', '0005_inventurnidoklad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surovina',
            name='koeficient_sk',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='1 = celé množství; <1 např. uzeniny dle % masa; >1 např. sušené/mléčné koncentráty dle metodiky.', max_digits=6, verbose_name='Koeficient pro spotřební koš'),
        ),
        migrations.AddField(
            model_name='surovina',
            name='skupina_sk',
            field=models.CharField(choices=[('NONE', 'Nezapočítávat do spotřebního koše'), ('MASO', 'Maso'), ('RYBY', 'Ryby'), ('MLEX', 'Mléko a mléčné výrobky'), ('OBIL', 'Obiloviny'), ('LUST', 'Luštěniny'), ('ZEL', 'Zelenina'), ('OVO', 'Ovoce'), ('BRAM', 'Brambory'), ('TUKY', 'Tuky'), ('CUKR', 'Cukr')], default='NONE', help_text='Do jaké skupiny spotřebního koše se surovina započítává.', max_length=10, verbose_name='Skupina spotřebního koše'),
        ),
        migrations.CreateModel(
            name='Vydejka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vekova_skupina', models.CharField(help_text='Např. MŠ, ZŠ 7–10, ZŠ 11–14…', max_length=50, verbose_name='Věková skupina')),
                ('typ_stravy', models.CharField(choices=[('OBED', 'Oběd'), ('CELD', 'Celodenní strava'), ('SVAC', 'Svačiny')], default='OBED', max_length=10, verbose_name='Typ stravy')),
                ('datum', models.DateField(verbose_name='Datum výdeje')),
                ('popis', models.CharField(blank=True, max_length=255, verbose_name='Poznámka')),
                ('uzavrena', models.BooleanField(default=False, verbose_name='Uzavřená (promítnuto do skladu a do výpočtu SK)')),
                ('jidla', models.ManyToManyField(blank=True, help_text='Pro přehled, k jakým jídlům se výdejka vztahuje.', to='jidelnicek.jidlo', verbose_name='Jídla v této výdejce')),
                ('vytvoril', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
            ],
            options={
                'verbose_name': 'Výdejka do výroby',
                'verbose_name_plural': 'Výdejky do výroby',
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='PolozkaVydejky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi', models.DecimalField(decimal_places=3, help_text='Ve stejné jednotce jako surovina.', max_digits=10, verbose_name='Množství')),
                ('surovina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.surovina', verbose_name='Surovina')),
                ('vydejka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='sklad.vydejka', verbose_name='Výdejka')),
            ],
            options={
                'verbose_name': 'Položka výdejky',
                'verbose_name_plural': 'Položky výdejky',
                'unique_together': {('vydejka', 'surovina')},
            },
        ),
    ]
