# Generated by Django 5.2.9 on 2026-03-10 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0006_surovina_koeficient_sk_surovina_skupina_sk_vydejka_and_more'),
        ('users', '0006_stravovaciskupina_customuser_stravovaci_skupina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vydejka',
            name='vekova_skupina',
        ),
        migrations.AddField(
            model_name='vydejka',
            name='stravovaci_skupina',
            field=models.ForeignKey(blank=True, help_text='Např. SŠ žáci, ZŠ 1. stupeň…', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.stravovaciskupina', verbose_name='Stravovací skupina'),
        ),
        migrations.AlterField(
            model_name='vydejka',
            name='typ_stravy',
            field=models.CharField(choices=[('OBED', 'Oběd'), ('CELD', 'Celodenní strava')], default='OBED', max_length=10, verbose_name='Typ stravy'),
        ),
    ]
