# Generated by Django 5.2.9 on 2026-03-10 16:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0007_remove_vydejka_vekova_skupina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PohybSkladu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum pohybu')),
                ('typ', models.CharField(choices=[('PRIJEM', 'Příjem'), ('VYDEJ', 'Výdej do výroby'), ('INVENTURA', 'Inventura')], max_length=20, verbose_name='Typ pohybu')),
                ('mnozstvi', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Množství (kladné číslo)')),
                ('poznamka', models.CharField(blank=True, max_length=255, verbose_name='Poznámka')),
                ('surovina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pohyby', to='sklad.surovina', verbose_name='Surovina')),
                ('vydejka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pohyby', to='sklad.vydejka', verbose_name='Výdejka')),
            ],
            options={
                'verbose_name': 'Pohyb na skladu',
                'verbose_name_plural': 'Pohyby na skladu',
                'ordering': ['-datum'],
            },
        ),
    ]
