# Generated by Django 5.2.9 on 2026-03-10 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0008_pohybskladu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pohybskladu',
            name='prijem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pohyby', to='sklad.prijemskladu', verbose_name='Příjem'),
        ),
    ]
