# Generated by Django 5.2.9 on 2026-03-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0009_pohybskladu_prijem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSpotrebniKos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Report spotřebního koše',
                'verbose_name_plural': 'Report spotřebního koše',
                'managed': False,
            },
        ),
    ]
