# Generated by Django 5.2.9 on 2026-03-10 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0010_reportspotrebnikos'),
        ('users', '0006_stravovaciskupina_customuser_stravovaci_skupina'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormaSpotrebnihoKose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skupina_sk', models.CharField(choices=[('NONE', 'Nezapočítávat do spotřebního koše'), ('MASO', 'Maso'), ('RYBY', 'Ryby'), ('MLEX', 'Mléko a mléčné výrobky'), ('OBIL', 'Obiloviny'), ('LUST', 'Luštěniny'), ('ZEL', 'Zelenina'), ('OVO', 'Ovoce'), ('BRAM', 'Brambory'), ('TUKY', 'Tuky'), ('CUKR', 'Cukr')], max_length=10, verbose_name='Skupina spotřebního koše')),
                ('norma_kg_mesic', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Norma (kg na 1 strávníka za měsíc)')),
                ('stravovaci_skupina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.stravovaciskupina', verbose_name='Stravovací skupina')),
            ],
            options={
                'verbose_name': 'Norma spotřebního koše',
                'verbose_name_plural': 'Normy spotřebního koše',
                'unique_together': {('stravovaci_skupina', 'skupina_sk')},
            },
        ),
    ]
