# Generated by Django 5.2.9 on 2026-03-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0011_normaspotrebnihokose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaspotrebnihokose',
            name='norma_kg_mesic',
        ),
        migrations.AddField(
            model_name='normaspotrebnihokose',
            name='norma_g_mesic',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Norma (g na 1 strávníka za měsíc)'),
            preserve_default=False,
        ),
    ]
