# Generated by Django 5.2.9 on 2026-03-15 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0012_remove_normaspotrebnihokose_norma_kg_mesic_and_more'),
        ('users', '0006_stravovaciskupina_customuser_stravovaci_skupina'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToleranceSpotrebnihoKose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skupina_sk', models.CharField(choices=[('NONE', 'Nezapočítávat do spotřebního koše'), ('MASO', 'Maso'), ('RYBY', 'Ryby'), ('MLEX', 'Mléko a mléčné výrobky'), ('OBIL', 'Obiloviny'), ('LUST', 'Luštěniny'), ('ZEL', 'Zelenina'), ('OVO', 'Ovoce'), ('BRAM', 'Brambory'), ('TUKY', 'Tuky'), ('CUKR', 'Cukr')], max_length=10, verbose_name='Skupina spotřebního koše')),
                ('min_pct', models.DecimalField(decimal_places=1, help_text='Dolní hranice tolerance v % (např. 75.0).', max_digits=5, verbose_name='Minimální % plnění')),
                ('max_pct', models.DecimalField(blank=True, decimal_places=1, help_text='Horní hranice tolerance v %; prázdné = bez horní hranice.', max_digits=5, null=True, verbose_name='Maximální % plnění')),
                ('stravovaci_skupina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolerance_sk', to='users.stravovaciskupina', verbose_name='Stravovací skupina')),
            ],
            options={
                'verbose_name': 'Tolerance spotřebního koše',
                'verbose_name_plural': 'Tolerance spotřebního koše',
                'unique_together': {('stravovaci_skupina', 'skupina_sk')},
            },
        ),
    ]
