# Generated by Django 5.2.9 on 2026-03-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0013_tolerancespotrebnihokose'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportNakladySkladu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Report nákladů na suroviny',
                'verbose_name_plural': 'Report nákladů na suroviny',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='pohybskladu',
            name='cena_za_jednotku',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Pro finanční evidenci skladu; u výdeje obvykle průměrná cena.', max_digits=10, null=True, verbose_name='Cena za jednotku'),
        ),
        migrations.AddField(
            model_name='polozkaprijmu',
            name='jednotkova_cena',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cena za 1 MJ (bez DPH nebo dle dohody).', max_digits=10, verbose_name='Jednotková cena'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prijemskladu',
            name='cislo_dokladu',
            field=models.CharField(blank=True, help_text='Číslo faktury / dodacího listu (nepovinné).', max_length=50, verbose_name='Číslo dokladu'),
        ),
        migrations.AddField(
            model_name='surovina',
            name='hmotnost_ks_g',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="Použije se při výpočtu spotřebního koše pro jednotku 'ks'.", max_digits=8, null=True, verbose_name='Hmotnost 1 ks v gramech'),
        ),
        migrations.AddField(
            model_name='surovina',
            name='prumerna_cena_za_jednotku',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Volitelné; může se aktualizovat z příjemek.', max_digits=10, null=True, verbose_name='Průměrná cena za jednotku'),
        ),
    ]
