# Generated by Django 5.2.9 on 2026-03-15 17:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0014_reportnakladyskladu_pohybskladu_cena_za_jednotku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surovina',
            name='je_bio',
            field=models.BooleanField(default=False, help_text='Započítává se do podílu bio potravin dle vyhlášky.', verbose_name='Biopotravina'),
        ),
        migrations.AddField(
            model_name='surovina',
            name='je_masny_vyrobek',
            field=models.BooleanField(default=False, help_text='Použije se pro výpočet podílu masných výrobků v mase.', verbose_name='Masný výrobek / polotovar'),
        ),
        migrations.AddField(
            model_name='surovina',
            name='podil_celozrnne_slozky',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Např. 0.30 pro 30 % celozrnné mouky v produktu.', max_digits=5, verbose_name='Podíl celozrnné složky'),
        ),
        migrations.AddField(
            model_name='surovina',
            name='volny_cukr_na_100g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pouze přidané cukry, med, sirupy apod., dle metodiky.', max_digits=6, null=True, verbose_name='Volný cukr na 100 g'),
        ),
        migrations.AlterField(
            model_name='normaspotrebnihokose',
            name='skupina_sk',
            field=models.CharField(choices=[('NONE', 'Nezapočítávat do spotřebního koše'), ('MASO', 'Maso'), ('RYBY', 'Ryby'), ('MLEX', 'Mléko a mléčné výrobky'), ('OBIL', 'Obiloviny'), ('COBIL', 'Celozrnné obiloviny a pseudoobiloviny'), ('LUST', 'Luštěniny'), ('ZEL', 'Zelenina'), ('OVO', 'Ovoce'), ('BRAM', 'Brambory'), ('TUKY', 'Tuky volné'), ('CUKR', 'Cukr volný')], max_length=10, verbose_name='Skupina spotřebního koše'),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='skupina_sk',
            field=models.CharField(choices=[('NONE', 'Nezapočítávat do spotřebního koše'), ('MASO', 'Maso'), ('RYBY', 'Ryby'), ('MLEX', 'Mléko a mléčné výrobky'), ('OBIL', 'Obiloviny'), ('COBIL', 'Celozrnné obiloviny a pseudoobiloviny'), ('LUST', 'Luštěniny'), ('ZEL', 'Zelenina'), ('OVO', 'Ovoce'), ('BRAM', 'Brambory'), ('TUKY', 'Tuky volné'), ('CUKR', 'Cukr volný')], default='NONE', help_text='Do jaké skupiny spotřebního koše se surovina započítává.', max_length=10, verbose_name='Skupina spotřebního koše'),
        ),
        migrations.AlterField(
            model_name='tolerancespotrebnihokose',
            name='skupina_sk',
            field=models.CharField(choices=[('NONE', 'Nezapočítávat do spotřebního koše'), ('MASO', 'Maso'), ('RYBY', 'Ryby'), ('MLEX', 'Mléko a mléčné výrobky'), ('OBIL', 'Obiloviny'), ('COBIL', 'Celozrnné obiloviny a pseudoobiloviny'), ('LUST', 'Luštěniny'), ('ZEL', 'Zelenina'), ('OVO', 'Ovoce'), ('BRAM', 'Brambory'), ('TUKY', 'Tuky volné'), ('CUKR', 'Cukr volný')], max_length=10, verbose_name='Skupina spotřebního koše'),
        ),
    ]
