# Generated by Django 5.2.9 on 2026-04-13 16:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jidelnicek', '0007_jidlo_foto'),
        ('sklad', '0015_surovina_je_bio_surovina_je_masny_vyrobek_and_more'),
        ('users', '0006_stravovaciskupina_customuser_stravovaci_skupina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportSpotrebniKos',
        ),
        migrations.AlterModelOptions(
            name='inventura',
            options={'verbose_name': 'Inventura', 'verbose_name_plural': 'Inventury'},
        ),
        migrations.AlterModelOptions(
            name='pohybskladu',
            options={'ordering': ('-datum', '-id'), 'verbose_name': 'Pohyb skladu', 'verbose_name_plural': 'Pohyby skladu'},
        ),
        migrations.AlterModelOptions(
            name='prijemskladu',
            options={'verbose_name': 'Příjemka', 'verbose_name_plural': 'Příjemky'},
        ),
        migrations.AlterModelOptions(
            name='recepturapolozka',
            options={'verbose_name': 'Položka receptury', 'verbose_name_plural': 'Položky receptury'},
        ),
        migrations.AlterModelOptions(
            name='reportnakladyskladu',
            options={'managed': False, 'verbose_name': 'Report nákladů skladu', 'verbose_name_plural': 'Report nákladů skladu'},
        ),
        migrations.AlterModelOptions(
            name='stavskladu',
            options={'ordering': ('surovina__nazev',), 'verbose_name': 'Stav skladu', 'verbose_name_plural': 'Stavy skladu'},
        ),
        migrations.AlterModelOptions(
            name='surovina',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vydejka',
            options={'verbose_name': 'Výdejka', 'verbose_name_plural': 'Výdejky'},
        ),
        migrations.AlterUniqueTogether(
            name='polozkainventury',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='polozkavydejky',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='recepturapolozka',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='inventura',
            name='uzavrena',
        ),
        migrations.RemoveField(
            model_name='prijemskladu',
            name='cislo_dokladu',
        ),
        migrations.RemoveField(
            model_name='vydejka',
            name='uzavrena',
        ),
        migrations.AddField(
            model_name='inventura',
            name='stornovano',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='inventura',
            name='stornovano_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventura',
            name='uzavrel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_uzavrel_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventura',
            name='uzavren_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventura',
            name='uzavreny',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='pohybskladu',
            name='inventura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pohyby', to='sklad.inventura'),
        ),
        migrations.AddField(
            model_name='prijemskladu',
            name='stornovano',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='prijemskladu',
            name='stornovano_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prijemskladu',
            name='uzavrel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_uzavrel_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prijemskladu',
            name='uzavren_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vydejka',
            name='stornovano',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='vydejka',
            name='stornovano_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vydejka',
            name='uzavrel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_uzavrel_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vydejka',
            name='uzavren_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vydejka',
            name='uzavreny',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='inventura',
            name='datum',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='inventura',
            name='popis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='inventura',
            name='vytvoril',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_vytvoril_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='normaspotrebnihokose',
            name='norma_g_mesic',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='normaspotrebnihokose',
            name='skupina_sk',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='normaspotrebnihokose',
            name='stravovaci_skupina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normy_sk', to='users.stravovaciskupina'),
        ),
        migrations.AlterField(
            model_name='pohybskladu',
            name='cena_za_jednotku',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='pohybskladu',
            name='datum',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pohybskladu',
            name='mnozstvi',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pohybskladu',
            name='poznamka',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pohybskladu',
            name='prijem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pohyby', to='sklad.prijemskladu'),
        ),
        migrations.AlterField(
            model_name='pohybskladu',
            name='surovina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pohyby', to='sklad.surovina'),
        ),
        migrations.AlterField(
            model_name='pohybskladu',
            name='typ',
            field=models.CharField(choices=[('PRIJEM', 'Příjem'), ('VYDEJ', 'Výdej'), ('INVENTURA_PLUS', 'Inventura +'), ('INVENTURA_MINUS', 'Inventura -')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pohybskladu',
            name='vydejka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pohyby', to='sklad.vydejka'),
        ),
        migrations.AlterField(
            model_name='polozkainventury',
            name='fyzicky_stav',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='polozkainventury',
            name='inventura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='sklad.inventura'),
        ),
        migrations.AlterField(
            model_name='polozkainventury',
            name='rozdil',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='polozkainventury',
            name='stav_pred',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='polozkainventury',
            name='surovina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.surovina'),
        ),
        migrations.AlterField(
            model_name='polozkaprijmu',
            name='jednotkova_cena',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='polozkaprijmu',
            name='mnozstvi',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='polozkaprijmu',
            name='prijem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='sklad.prijemskladu'),
        ),
        migrations.AlterField(
            model_name='polozkaprijmu',
            name='surovina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.surovina'),
        ),
        migrations.AlterField(
            model_name='polozkavydejky',
            name='mnozstvi',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='polozkavydejky',
            name='surovina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.surovina'),
        ),
        migrations.AlterField(
            model_name='polozkavydejky',
            name='vydejka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='sklad.vydejka'),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='datum',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='popis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='uzavreny',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='vytvoril',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_vytvoril_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recepturapolozka',
            name='mnozstvi_na_porci',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='recepturapolozka',
            name='surovina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.surovina'),
        ),
        migrations.AlterField(
            model_name='stavskladu',
            name='min_mnozstvi',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stavskladu',
            name='mnozstvi',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='hmotnost_ks_g',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='je_bio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='je_masny_vyrobek',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='jednotka',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('l', 'l'), ('ml', 'ml'), ('ks', 'ks')], max_length=10),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='koeficient_sk',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='nazev',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='podil_celozrnne_slozky',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='prumerna_cena_za_jednotku',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='skupina_sk',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='volny_cukr_na_100g',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tolerancespotrebnihokose',
            name='max_pct',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tolerancespotrebnihokose',
            name='min_pct',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tolerancespotrebnihokose',
            name='skupina_sk',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tolerancespotrebnihokose',
            name='stravovaci_skupina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolerance_sk', to='users.stravovaciskupina'),
        ),
        migrations.AlterField(
            model_name='vydejka',
            name='datum',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='vydejka',
            name='jidla',
            field=models.ManyToManyField(blank=True, related_name='vydejky', to='jidelnicek.jidlo'),
        ),
        migrations.AlterField(
            model_name='vydejka',
            name='popis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vydejka',
            name='stravovaci_skupina',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.PROTECT, related_name='vydejky', to='users.stravovaciskupina'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vydejka',
            name='typ_stravy',
            field=models.CharField(choices=[('OBED', 'Oběd'), ('SVACINA', 'Svačina'), ('VECERE', 'Večeře')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vydejka',
            name='vytvoril',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_vytvoril_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='vydejka',
            constraint=models.UniqueConstraint(fields=('datum', 'stravovaci_skupina', 'typ_stravy'), name='uniq_vydejka_per_den_skupina_typ'),
        ),
    ]
