# Generated by Django 5.2.9 on 2026-04-13 19:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jidelnicek', '0007_jidlo_foto'),
        ('sklad', '0016_delete_reportspotrebnikos_alter_inventura_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KomponentaJidla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=255, unique=True)),
                ('typ', models.CharField(choices=[('POLEVKA', 'Polévka'), ('OMACKA', 'Omáčka / základ'), ('MASO', 'Maso / protein'), ('PRILOHA', 'Příloha'), ('SALAT', 'Salát'), ('DEZERT', 'Dezert'), ('NAPOJ', 'Nápoj'), ('OSTATNI', 'Ostatní')], db_index=True, default='OSTATNI', max_length=20)),
                ('aktivni', models.BooleanField(default=True)),
                ('poznamka', models.TextField(blank=True, default='')),
                ('porce_text', models.CharField(blank=True, default='', help_text='Např. 150 ml, 2 ks, 180 g', max_length=100)),
            ],
            options={
                'verbose_name': 'Komponenta jídla',
                'verbose_name_plural': 'Komponenty jídel',
                'ordering': ('typ', 'nazev'),
            },
        ),
        migrations.CreateModel(
            name='JidloKomponenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi_nasobek', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='1.0 = standardní porce komponenty, 0.5 = půl porce, 2.0 = dvojnásobek', max_digits=8)),
                ('poradi', models.PositiveIntegerField(default=0)),
                ('povinna', models.BooleanField(default=True)),
                ('jidlo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komponenty_jidla', to='jidelnicek.jidlo')),
                ('komponenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jidla', to='sklad.komponentajidla')),
            ],
            options={
                'verbose_name': 'Komponenta v jídle',
                'verbose_name_plural': 'Komponenty v jídlech',
                'ordering': ('poradi', 'id'),
                'unique_together': {('jidlo', 'komponenta')},
            },
        ),
        migrations.CreateModel(
            name='KomponentaSurovina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi_na_porci', models.DecimalField(decimal_places=3, max_digits=12)),
                ('komponenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suroviny', to='sklad.komponentajidla')),
                ('surovina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.surovina')),
            ],
            options={
                'verbose_name': 'Surovina komponenty',
                'verbose_name_plural': 'Suroviny komponenty',
                'ordering': ('komponenta__nazev', 'surovina__nazev'),
                'unique_together': {('komponenta', 'surovina')},
            },
        ),
    ]
