# Generated by Django for sklad receiving-document improvements.

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sklad", "0017_komponentajidla_jidlokomponenta_komponentasurovina"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dodavatel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nazev", models.CharField(max_length=255, unique=True)),
                ("ico", models.CharField(blank=True, default="", max_length=20)),
                ("dic", models.CharField(blank=True, default="", max_length=20)),
                ("adresa", models.TextField(blank=True, default="")),
                ("kontaktni_osoba", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("telefon", models.CharField(blank=True, default="", max_length=50)),
                ("aktivni", models.BooleanField(default=True)),
                ("poznamka", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Dodavatel",
                "verbose_name_plural": "Dodavatelé",
                "ordering": ("nazev",),
            },
        ),
        migrations.AddField(
            model_name="polozkaprijmu",
            name="cena_celkem_bez_dph",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="polozkaprijmu",
            name="cena_celkem_s_dph",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="polozkaprijmu",
            name="cena_za_baleni_bez_dph",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="polozkaprijmu",
            name="cena_za_baleni_s_dph",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="polozkaprijmu",
            name="datum_spotreby",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="polozkaprijmu",
            name="jednotka_baleni",
            field=models.CharField(
                blank=True,
                choices=[("g", "g"), ("kg", "kg"), ("l", "l"), ("ml", "ml"), ("ks", "ks")],
                default="",
                help_text="Pokud zůstane prázdná, použije se skladová jednotka suroviny.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="polozkaprijmu",
            name="mnozstvi_v_baleni",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Množství v jednom dodaném balení.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="polozkaprijmu",
            name="pocet_baleni",
            field=models.DecimalField(decimal_places=3, default=Decimal("1.000"), max_digits=12),
        ),
        migrations.AddField(
            model_name="polozkaprijmu",
            name="sarze",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="polozkaprijmu",
            name="sazba_dph",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
        ),
        migrations.AddField(
            model_name="prijemskladu",
            name="castka_faktury_celkem",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="prijemskladu",
            name="cislo_dodaciho_listu",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="prijemskladu",
            name="cislo_faktury",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="prijemskladu",
            name="datum_dodani",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prijemskladu",
            name="datum_splatnosti",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prijemskladu",
            name="datum_vystaveni",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prijemskladu",
            name="priloha",
            field=models.FileField(blank=True, null=True, upload_to="sklad/prijemky/"),
        ),
        migrations.AlterField(
            model_name="polozkaprijmu",
            name="jednotkova_cena",
            field=models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12),
        ),
        migrations.AlterField(
            model_name="polozkaprijmu",
            name="mnozstvi",
            field=models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=12),
        ),
        migrations.AddField(
            model_name="prijemskladu",
            name="dodavatel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prijemky",
                to="sklad.dodavatel",
            ),
        ),
    ]
