# Generated by Django 5.2.9 on 2026-04-14 12:32

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jidelnicek', '0007_jidlo_foto'),
        ('sklad', '0018_dodavatel_polozkaprijmu_cena_celkem_bez_dph_and_more'),
        ('users', '0006_stravovaciskupina_customuser_stravovaci_skupina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodavatel',
            name='adresa',
            field=models.TextField(blank=True, default='', verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='dodavatel',
            name='aktivni',
            field=models.BooleanField(default=True, verbose_name='Aktivní'),
        ),
        migrations.AlterField(
            model_name='dodavatel',
            name='dic',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='DIČ'),
        ),
        migrations.AlterField(
            model_name='dodavatel',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='dodavatel',
            name='ico',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='IČO'),
        ),
        migrations.AlterField(
            model_name='dodavatel',
            name='kontaktni_osoba',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Kontaktní osoba'),
        ),
        migrations.AlterField(
            model_name='dodavatel',
            name='nazev',
            field=models.CharField(max_length=255, unique=True, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='dodavatel',
            name='poznamka',
            field=models.TextField(blank=True, default='', verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='dodavatel',
            name='telefon',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='inventura',
            name='datum',
            field=models.DateField(db_index=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='inventura',
            name='popis',
            field=models.TextField(blank=True, default='', verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='inventura',
            name='stornovano',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Stornováno'),
        ),
        migrations.AlterField(
            model_name='inventura',
            name='stornovano_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stornováno dne'),
        ),
        migrations.AlterField(
            model_name='inventura',
            name='uzavrel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_uzavrel_set', to=settings.AUTH_USER_MODEL, verbose_name='Uzavřel'),
        ),
        migrations.AlterField(
            model_name='inventura',
            name='uzavren_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Uzavřeno'),
        ),
        migrations.AlterField(
            model_name='inventura',
            name='uzavreny',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Uzavřený'),
        ),
        migrations.AlterField(
            model_name='inventura',
            name='vytvoril',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_vytvoril_set', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil'),
        ),
        migrations.AlterField(
            model_name='jidlokomponenta',
            name='jidlo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komponenty_jidla', to='jidelnicek.jidlo', verbose_name='Jídlo'),
        ),
        migrations.AlterField(
            model_name='jidlokomponenta',
            name='komponenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jidla', to='sklad.komponentajidla', verbose_name='Komponenta'),
        ),
        migrations.AlterField(
            model_name='jidlokomponenta',
            name='mnozstvi_nasobek',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='1.0 = standardní porce komponenty, 0.5 = půl porce, 2.0 = dvojnásobek', max_digits=8, verbose_name='Násobek množství'),
        ),
        migrations.AlterField(
            model_name='jidlokomponenta',
            name='poradi',
            field=models.PositiveIntegerField(default=0, verbose_name='Pořadí'),
        ),
        migrations.AlterField(
            model_name='jidlokomponenta',
            name='povinna',
            field=models.BooleanField(default=True, verbose_name='Povinná'),
        ),
        migrations.AlterField(
            model_name='komponentajidla',
            name='aktivni',
            field=models.BooleanField(default=True, verbose_name='Aktivní'),
        ),
        migrations.AlterField(
            model_name='komponentajidla',
            name='nazev',
            field=models.CharField(max_length=255, unique=True, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='komponentajidla',
            name='porce_text',
            field=models.CharField(blank=True, default='', help_text='Např. 150 ml, 2 ks, 180 g', max_length=100, verbose_name='Text porce'),
        ),
        migrations.AlterField(
            model_name='komponentajidla',
            name='poznamka',
            field=models.TextField(blank=True, default='', verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='komponentajidla',
            name='typ',
            field=models.CharField(choices=[('POLEVKA', 'Polévka'), ('OMACKA', 'Omáčka / základ'), ('MASO', 'Maso / protein'), ('PRILOHA', 'Příloha'), ('SALAT', 'Salát'), ('DEZERT', 'Dezert'), ('NAPOJ', 'Nápoj'), ('OSTATNI', 'Ostatní')], db_index=True, default='OSTATNI', max_length=20, verbose_name='Typ komponenty'),
        ),
        migrations.AlterField(
            model_name='komponentasurovina',
            name='komponenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suroviny', to='sklad.komponentajidla', verbose_name='Komponenta'),
        ),
        migrations.AlterField(
            model_name='komponentasurovina',
            name='mnozstvi_na_porci',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Množství na porci'),
        ),
        migrations.AlterField(
            model_name='komponentasurovina',
            name='surovina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.surovina', verbose_name='Surovina'),
        ),
        migrations.AlterField(
            model_name='normaspotrebnihokose',
            name='norma_g_mesic',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Měsíční norma [g]'),
        ),
        migrations.AlterField(
            model_name='normaspotrebnihokose',
            name='skupina_sk',
            field=models.CharField(max_length=50, verbose_name='Skupina spotřebního koše'),
        ),
        migrations.AlterField(
            model_name='normaspotrebnihokose',
            name='stravovaci_skupina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normy_sk', to='users.stravovaciskupina', verbose_name='Stravovací skupina'),
        ),
        migrations.AlterField(
            model_name='pohybskladu',
            name='cena_za_jednotku',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Cena za jednotku'),
        ),
        migrations.AlterField(
            model_name='pohybskladu',
            name='datum',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='pohybskladu',
            name='inventura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pohyby', to='sklad.inventura', verbose_name='Inventura'),
        ),
        migrations.AlterField(
            model_name='pohybskladu',
            name='mnozstvi',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Množství'),
        ),
        migrations.AlterField(
            model_name='pohybskladu',
            name='poznamka',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='pohybskladu',
            name='prijem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pohyby', to='sklad.prijemskladu', verbose_name='Příjemka'),
        ),
        migrations.AlterField(
            model_name='pohybskladu',
            name='surovina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pohyby', to='sklad.surovina', verbose_name='Surovina'),
        ),
        migrations.AlterField(
            model_name='pohybskladu',
            name='typ',
            field=models.CharField(choices=[('PRIJEM', 'Příjem'), ('VYDEJ', 'Výdej'), ('INVENTURA_PLUS', 'Inventura +'), ('INVENTURA_MINUS', 'Inventura -')], db_index=True, max_length=20, verbose_name='Typ pohybu'),
        ),
        migrations.AlterField(
            model_name='pohybskladu',
            name='vydejka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pohyby', to='sklad.vydejka', verbose_name='Výdejka'),
        ),
        migrations.AlterField(
            model_name='polozkainventury',
            name='fyzicky_stav',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Fyzický stav'),
        ),
        migrations.AlterField(
            model_name='polozkainventury',
            name='inventura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='sklad.inventura', verbose_name='Inventura'),
        ),
        migrations.AlterField(
            model_name='polozkainventury',
            name='rozdil',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Rozdíl'),
        ),
        migrations.AlterField(
            model_name='polozkainventury',
            name='stav_pred',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Stav před inventurou'),
        ),
        migrations.AlterField(
            model_name='polozkainventury',
            name='surovina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.surovina', verbose_name='Surovina'),
        ),
        migrations.AlterField(
            model_name='polozkaprijmu',
            name='cena_celkem_bez_dph',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Cena celkem bez DPH'),
        ),
        migrations.AlterField(
            model_name='polozkaprijmu',
            name='cena_celkem_s_dph',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Cena celkem s DPH'),
        ),
        migrations.AlterField(
            model_name='polozkaprijmu',
            name='cena_za_baleni_bez_dph',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Cena za balení bez DPH'),
        ),
        migrations.AlterField(
            model_name='polozkaprijmu',
            name='cena_za_baleni_s_dph',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Cena za balení s DPH'),
        ),
        migrations.AlterField(
            model_name='polozkaprijmu',
            name='datum_spotreby',
            field=models.DateField(blank=True, null=True, verbose_name='Datum spotřeby'),
        ),
        migrations.AlterField(
            model_name='polozkaprijmu',
            name='jednotka_baleni',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('l', 'l'), ('ml', 'ml'), ('ks', 'ks')], default='', help_text='Pokud zůstane prázdná, použije se skladová jednotka suroviny.', max_length=10, verbose_name='Jednotka balení'),
        ),
        migrations.AlterField(
            model_name='polozkaprijmu',
            name='jednotkova_cena',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Jednotková cena'),
        ),
        migrations.AlterField(
            model_name='polozkaprijmu',
            name='mnozstvi',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Množství'),
        ),
        migrations.AlterField(
            model_name='polozkaprijmu',
            name='mnozstvi_v_baleni',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Množství v jednom dodaném balení.', max_digits=12, null=True, verbose_name='Množství v balení'),
        ),
        migrations.AlterField(
            model_name='polozkaprijmu',
            name='pocet_baleni',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12, verbose_name='Počet balení'),
        ),
        migrations.AlterField(
            model_name='polozkaprijmu',
            name='prijem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='sklad.prijemskladu', verbose_name='Příjemka'),
        ),
        migrations.AlterField(
            model_name='polozkaprijmu',
            name='sarze',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Šarže'),
        ),
        migrations.AlterField(
            model_name='polozkaprijmu',
            name='sazba_dph',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Sazba DPH [%]'),
        ),
        migrations.AlterField(
            model_name='polozkaprijmu',
            name='surovina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.surovina', verbose_name='Surovina'),
        ),
        migrations.AlterField(
            model_name='polozkavydejky',
            name='mnozstvi',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Množství'),
        ),
        migrations.AlterField(
            model_name='polozkavydejky',
            name='surovina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.surovina', verbose_name='Surovina'),
        ),
        migrations.AlterField(
            model_name='polozkavydejky',
            name='vydejka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='sklad.vydejka', verbose_name='Výdejka'),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='castka_faktury_celkem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Částka faktury celkem'),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='cislo_dodaciho_listu',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Číslo dodacího listu'),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='cislo_faktury',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Číslo faktury'),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='datum',
            field=models.DateField(db_index=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='datum_dodani',
            field=models.DateField(blank=True, null=True, verbose_name='Datum dodání'),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='datum_splatnosti',
            field=models.DateField(blank=True, null=True, verbose_name='Datum splatnosti'),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='datum_vystaveni',
            field=models.DateField(blank=True, null=True, verbose_name='Datum vystavení'),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='dodavatel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prijemky', to='sklad.dodavatel', verbose_name='Dodavatel'),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='popis',
            field=models.TextField(blank=True, default='', verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='priloha',
            field=models.FileField(blank=True, null=True, upload_to='sklad/prijemky/', verbose_name='Příloha'),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='stornovano',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Stornováno'),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='stornovano_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stornováno dne'),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='uzavrel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_uzavrel_set', to=settings.AUTH_USER_MODEL, verbose_name='Uzavřel'),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='uzavren_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Uzavřeno'),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='uzavreny',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Uzavřený'),
        ),
        migrations.AlterField(
            model_name='prijemskladu',
            name='vytvoril',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_vytvoril_set', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil'),
        ),
        migrations.AlterField(
            model_name='recepturapolozka',
            name='jidlo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptura', to='jidelnicek.jidlo', verbose_name='Jídlo'),
        ),
        migrations.AlterField(
            model_name='recepturapolozka',
            name='mnozstvi_na_porci',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Množství na porci'),
        ),
        migrations.AlterField(
            model_name='recepturapolozka',
            name='surovina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.surovina', verbose_name='Surovina'),
        ),
        migrations.AlterField(
            model_name='stavskladu',
            name='min_mnozstvi',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Minimální množství'),
        ),
        migrations.AlterField(
            model_name='stavskladu',
            name='mnozstvi',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Množství'),
        ),
        migrations.AlterField(
            model_name='stavskladu',
            name='surovina',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stav', to='sklad.surovina', verbose_name='Surovina'),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='hmotnost_ks_g',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Hmotnost 1 ks [g]'),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='je_bio',
            field=models.BooleanField(default=False, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='je_masny_vyrobek',
            field=models.BooleanField(default=False, verbose_name='Masný výrobek'),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='jednotka',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('l', 'l'), ('ml', 'ml'), ('ks', 'ks')], max_length=10, verbose_name='Jednotka'),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='koeficient_sk',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=8, verbose_name='Koeficient spotřebního koše'),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='nazev',
            field=models.CharField(max_length=255, unique=True, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='podil_celozrnne_slozky',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Podíl celozrnné složky [%]'),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='prumerna_cena_za_jednotku',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Průměrná cena za jednotku'),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='skupina_sk',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Skupina spotřebního koše'),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='volny_cukr_na_100g',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Volný cukr na 100 g'),
        ),
        migrations.AlterField(
            model_name='tolerancespotrebnihokose',
            name='max_pct',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Maximum [%]'),
        ),
        migrations.AlterField(
            model_name='tolerancespotrebnihokose',
            name='min_pct',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Minimum [%]'),
        ),
        migrations.AlterField(
            model_name='tolerancespotrebnihokose',
            name='skupina_sk',
            field=models.CharField(max_length=50, verbose_name='Skupina spotřebního koše'),
        ),
        migrations.AlterField(
            model_name='tolerancespotrebnihokose',
            name='stravovaci_skupina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolerance_sk', to='users.stravovaciskupina', verbose_name='Stravovací skupina'),
        ),
        migrations.AlterField(
            model_name='vydejka',
            name='datum',
            field=models.DateField(db_index=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='vydejka',
            name='jidla',
            field=models.ManyToManyField(blank=True, related_name='vydejky', to='jidelnicek.jidlo', verbose_name='Jídla'),
        ),
        migrations.AlterField(
            model_name='vydejka',
            name='popis',
            field=models.TextField(blank=True, default='', verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='vydejka',
            name='stornovano',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Stornováno'),
        ),
        migrations.AlterField(
            model_name='vydejka',
            name='stornovano_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stornováno dne'),
        ),
        migrations.AlterField(
            model_name='vydejka',
            name='stravovaci_skupina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vydejky', to='users.stravovaciskupina', verbose_name='Stravovací skupina'),
        ),
        migrations.AlterField(
            model_name='vydejka',
            name='typ_stravy',
            field=models.CharField(choices=[('OBED', 'Oběd'), ('SVACINA', 'Svačina'), ('VECERE', 'Večeře')], db_index=True, max_length=20, verbose_name='Typ stravy'),
        ),
        migrations.AlterField(
            model_name='vydejka',
            name='uzavrel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_uzavrel_set', to=settings.AUTH_USER_MODEL, verbose_name='Uzavřel'),
        ),
        migrations.AlterField(
            model_name='vydejka',
            name='uzavren_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Uzavřeno'),
        ),
        migrations.AlterField(
            model_name='vydejka',
            name='uzavreny',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Uzavřený'),
        ),
        migrations.AlterField(
            model_name='vydejka',
            name='vytvoril',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_vytvoril_set', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil'),
        ),
    ]
