# Generated by Django 5.2.9 on 2026-04-14 12:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0019_alter_dodavatel_adresa_alter_dodavatel_aktivni_and_more'),
        ('users', '0006_stravovaciskupina_customuser_stravovaci_skupina'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='normaspotrebnihokose',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='normaspotrebnihokose',
            name='norma_g_den',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Denní norma [g / strávník / den]'),
        ),
        migrations.AddField(
            model_name='normaspotrebnihokose',
            name='typ_jidla',
            field=models.CharField(choices=[('SNIDANE', 'Snídaně'), ('PRESNIDAVKA', 'Přesnídávka'), ('OBED', 'Oběd'), ('SVACINA', 'Svačina'), ('VECERE', 'Večeře'), ('PRESNIDAVKA_OBED_SVACINA', 'Přesnídávka, oběd a svačina'), ('CELODENNI', 'Celodenní stravování')], default='OBED', max_length=40, verbose_name='Typ jídla'),
        ),
        migrations.AddField(
            model_name='normaspotrebnihokose',
            name='vekova_kategorie',
            field=models.CharField(choices=[('2_3', '2-3 roky'), ('4_6', '4-6 let'), ('7_10', '7-10 let'), ('11_14', '11-14 let'), ('15_PLUS', '15 a více let')], default='15_PLUS', max_length=20, verbose_name='Věková kategorie'),
        ),
        migrations.AddField(
            model_name='surovina',
            name='je_rostlinny_tuk',
            field=models.BooleanField(default=False, verbose_name='Rostlinný volný tuk'),
        ),
        migrations.AddField(
            model_name='surovina',
            name='je_sezonni',
            field=models.BooleanField(default=False, verbose_name='Sezónní ovoce, zelenina nebo brambory'),
        ),
        migrations.AddField(
            model_name='surovina',
            name='je_sterilovana_nebo_kompot',
            field=models.BooleanField(default=False, help_text='Sleduje limit 15 % ve skupině Zelenina, ovoce.', verbose_name='Sterilovaná zelenina / kompot'),
        ),
        migrations.AddField(
            model_name='surovina',
            name='je_zakazano_pro_skolni_stravovani',
            field=models.BooleanField(default=False, verbose_name='Zakázáno pro školní stravování'),
        ),
        migrations.AddField(
            model_name='surovina',
            name='je_zivocisny_tuk',
            field=models.BooleanField(default=False, verbose_name='Živočišný volný tuk'),
        ),
        migrations.AddField(
            model_name='surovina',
            name='koeficient_ciste_hmotnosti_sk',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Násobek hrubé hmotnosti pro přepočet na čistou hmotnost podle vyhlášky.', max_digits=8, verbose_name='Koeficient čisté hmotnosti'),
        ),
        migrations.AddField(
            model_name='surovina',
            name='koeficient_zapoctu_sk',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Koeficient započtení čisté hmotnosti podle tabulky potravin ve vyhlášce.', max_digits=8, verbose_name='Započítávací koeficient'),
        ),
        migrations.AlterField(
            model_name='normaspotrebnihokose',
            name='norma_g_mesic',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Zastaralé pole ponechané kvůli kompatibilitě; nový výpočet používá denní normu.', max_digits=12, verbose_name='Měsíční norma [g]'),
        ),
        migrations.AlterField(
            model_name='normaspotrebnihokose',
            name='skupina_sk',
            field=models.CharField(choices=[('MASO', 'Maso'), ('RYBY', 'Ryby, korýši, měkkýši'), ('MLEKO', 'Mléčné výrobky, mléko'), ('TUKY', 'Tuky volné'), ('CUKRY', 'Cukry volné'), ('ZELENINA_OVOCE', 'Zelenina, ovoce'), ('BRAMBORY', 'Brambory a ostatní hlízy'), ('CELOZRNNE', 'Celozrnné obiloviny, pseudoobiloviny'), ('LUSTENINY', 'Luštěniny'), ('NEZAPOCITAVA_SE', 'Nezapočítává se')], max_length=50, verbose_name='Skupina spotřebního koše'),
        ),
        migrations.AlterField(
            model_name='normaspotrebnihokose',
            name='stravovaci_skupina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normy_sk', to='users.stravovaciskupina', verbose_name='Stravovací skupina'),
        ),
        migrations.AlterField(
            model_name='surovina',
            name='skupina_sk',
            field=models.CharField(blank=True, choices=[('MASO', 'Maso'), ('RYBY', 'Ryby, korýši, měkkýši'), ('MLEKO', 'Mléčné výrobky, mléko'), ('TUKY', 'Tuky volné'), ('CUKRY', 'Cukry volné'), ('ZELENINA_OVOCE', 'Zelenina, ovoce'), ('BRAMBORY', 'Brambory a ostatní hlízy'), ('CELOZRNNE', 'Celozrnné obiloviny, pseudoobiloviny'), ('LUSTENINY', 'Luštěniny'), ('NEZAPOCITAVA_SE', 'Nezapočítává se')], default='', max_length=50, verbose_name='Skupina spotřebního koše'),
        ),
        migrations.AlterField(
            model_name='tolerancespotrebnihokose',
            name='max_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prázdná hodnota znamená, že horní limit není stanoven.', max_digits=8, null=True, verbose_name='Maximum [%]'),
        ),
        migrations.AlterField(
            model_name='tolerancespotrebnihokose',
            name='skupina_sk',
            field=models.CharField(choices=[('MASO', 'Maso'), ('RYBY', 'Ryby, korýši, měkkýši'), ('MLEKO', 'Mléčné výrobky, mléko'), ('TUKY', 'Tuky volné'), ('CUKRY', 'Cukry volné'), ('ZELENINA_OVOCE', 'Zelenina, ovoce'), ('BRAMBORY', 'Brambory a ostatní hlízy'), ('CELOZRNNE', 'Celozrnné obiloviny, pseudoobiloviny'), ('LUSTENINY', 'Luštěniny'), ('NEZAPOCITAVA_SE', 'Nezapočítává se')], max_length=50, verbose_name='Skupina spotřebního koše'),
        ),
        migrations.AlterField(
            model_name='tolerancespotrebnihokose',
            name='stravovaci_skupina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tolerance_sk', to='users.stravovaciskupina', verbose_name='Stravovací skupina'),
        ),
        migrations.AlterUniqueTogether(
            name='normaspotrebnihokose',
            unique_together={('vekova_kategorie', 'typ_jidla', 'skupina_sk', 'stravovaci_skupina')},
        ),
    ]
