# Generated by Django 5.2.9 on 2026-04-14 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jidelnicek', '0008_jidlo_sk_bezmasy_pokrm_jidlo_sk_bile_maso_and_more'),
        ('sklad', '0020_alter_normaspotrebnihokose_unique_together_and_more'),
        ('users', '0006_stravovaciskupina_customuser_stravovaci_skupina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vydejka',
            name='uniq_vydejka_per_den_skupina_typ',
        ),
        migrations.AddConstraint(
            model_name='vydejka',
            constraint=models.UniqueConstraint(condition=models.Q(('stornovano', False)), fields=('datum', 'stravovaci_skupina', 'typ_stravy'), name='uniq_vydejka_per_den_skupina_typ'),
        ),
    ]
