# Generated by Django 5.2.9 on 2026-04-14 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0021_remove_vydejka_uniq_vydejka_per_den_skupina_typ_and_more'),
        ('users', '0006_stravovaciskupina_customuser_stravovaci_skupina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vydejka',
            name='stravovaci_skupina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vydejky', to='users.stravovaciskupina', verbose_name='Stravovací skupina'),
        ),
        migrations.AlterField(
            model_name='vydejka',
            name='typ_stravy',
            field=models.CharField(blank=True, choices=[('OBED', 'Oběd'), ('SVACINA', 'Svačina'), ('VECERE', 'Večeře')], db_index=True, default='', max_length=20, verbose_name='Typ stravy'),
        ),
    ]
