# Generated by Django 5.2.9 on 2026-04-14 18:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0022_alter_vydejka_stravovaci_skupina_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='polozkaprijmu',
            name='typ_data_spotreby',
            field=models.CharField(choices=[('POUZITELNOST', 'Spotřebujte do'), ('MINIMALNI_TRVANLIVOST', 'Minimální trvanlivost do'), ('NEUVADI_SE', 'Neuvádí se')], default='POUZITELNOST', max_length=30, verbose_name='Typ data spotřeby'),
        ),
        migrations.AlterField(
            model_name='pohybskladu',
            name='typ',
            field=models.CharField(choices=[('PRIJEM', 'Příjem'), ('VYDEJ', 'Výdej'), ('INVENTURA_PLUS', 'Inventura +'), ('INVENTURA_MINUS', 'Inventura -'), ('EXPIRACE_MINUS', 'Odpis expirace'), ('KARANTENA_DMT', 'Karanténa po minimální trvanlivosti')], db_index=True, max_length=20, verbose_name='Typ pohybu'),
        ),
        migrations.CreateModel(
            name='OdpisExpirace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(db_index=True, verbose_name='Datum')),
                ('popis', models.TextField(blank=True, default='', verbose_name='Popis')),
                ('uzavreny', models.BooleanField(db_index=True, default=False, verbose_name='Uzavřený')),
                ('uzavren_at', models.DateTimeField(blank=True, null=True, verbose_name='Uzavřeno')),
                ('stornovano', models.BooleanField(db_index=True, default=False, verbose_name='Stornováno')),
                ('stornovano_at', models.DateTimeField(blank=True, null=True, verbose_name='Stornováno dne')),
                ('uzavrel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_uzavrel_set', to=settings.AUTH_USER_MODEL, verbose_name='Uzavřel')),
                ('vytvoril', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_vytvoril_set', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
            ],
            options={
                'verbose_name': 'Odpis expirace',
                'verbose_name_plural': 'Odpisy expirací',
            },
        ),
        migrations.AddField(
            model_name='pohybskladu',
            name='odpis_expirace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pohyby', to='sklad.odpisexpirace', verbose_name='Odpis expirace'),
        ),
        migrations.CreateModel(
            name='SarzeSkladu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarze', models.CharField(blank=True, default='', max_length=100, verbose_name='Šarže')),
                ('typ_data_spotreby', models.CharField(choices=[('POUZITELNOST', 'Spotřebujte do'), ('MINIMALNI_TRVANLIVOST', 'Minimální trvanlivost do'), ('NEUVADI_SE', 'Neuvádí se')], default='POUZITELNOST', max_length=30, verbose_name='Typ data spotřeby')),
                ('datum_spotreby', models.DateField(blank=True, db_index=True, null=True, verbose_name='Datum spotřeby')),
                ('mnozstvi_prijato', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Přijato')),
                ('mnozstvi_zbyva', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Zbývá')),
                ('cena_za_jednotku', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Cena za jednotku')),
                ('stav', models.CharField(choices=[('POUZITELNA', 'Použitelná'), ('KARANTENA', 'Karanténa'), ('EXPIROVANA', 'Expirovaná'), ('ODEPSANA', 'Odepsaná')], db_index=True, default='POUZITELNA', max_length=30, verbose_name='Stav')),
                ('poznamka', models.TextField(blank=True, default='', verbose_name='Poznámka')),
                ('polozka_prijmu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sarze_skladu', to='sklad.polozkaprijmu', verbose_name='Položka příjmu')),
                ('surovina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sarze_skladu', to='sklad.surovina', verbose_name='Surovina')),
            ],
            options={
                'verbose_name': 'Šarže skladu',
                'verbose_name_plural': 'Šarže skladu',
                'ordering': ('datum_spotreby', 'surovina__nazev', 'id'),
            },
        ),
        migrations.AddField(
            model_name='pohybskladu',
            name='sarze_skladu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pohyby', to='sklad.sarzeskladu', verbose_name='Šarže skladu'),
        ),
        migrations.AddIndex(
            model_name='sarzeskladu',
            index=models.Index(fields=['surovina', 'stav', 'datum_spotreby'], name='sklad_sarze_surovin_2ee18c_idx'),
        ),
    ]
