# Generated by Django 5.2.9 on 2026-04-15 14:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0023_polozkaprijmu_typ_data_spotreby_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkladovaUzaverka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(db_index=True, verbose_name='Datum')),
                ('popis', models.TextField(blank=True, default='', verbose_name='Popis')),
                ('uzavreny', models.BooleanField(db_index=True, default=False, verbose_name='Uzavřený')),
                ('uzavren_at', models.DateTimeField(blank=True, null=True, verbose_name='Uzavřeno')),
                ('stornovano', models.BooleanField(db_index=True, default=False, verbose_name='Stornováno')),
                ('stornovano_at', models.DateTimeField(blank=True, null=True, verbose_name='Stornováno dne')),
                ('rok', models.PositiveSmallIntegerField(db_index=True, verbose_name='Rok')),
                ('mesic', models.PositiveSmallIntegerField(db_index=True, verbose_name='Měsíc')),
                ('pocatecni_stav', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Počáteční hodnota skladu')),
                ('prijmy', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Příjmy')),
                ('storna_prijmu', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Storna příjmů')),
                ('vydeje', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Výdeje')),
                ('storna_vydeju', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Storna výdejek')),
                ('odpisy_expirace', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Odpisy expirací')),
                ('inventura_plus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Inventurní přebytky')),
                ('inventura_minus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Inventurní manka')),
                ('vypocet_konecneho_stavu', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Vypočtená konečná hodnota')),
                ('konecny_stav', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Skutečná konečná hodnota')),
                ('rozdil_kontroly', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Kontrolní rozdíl')),
                ('uzavrel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_uzavrel_set', to=settings.AUTH_USER_MODEL, verbose_name='Uzavřel')),
                ('vytvoril', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_vytvoril_set', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
            ],
            options={
                'verbose_name': 'Skladová uzávěrka',
                'verbose_name_plural': 'Skladové uzávěrky',
                'constraints': [models.UniqueConstraint(fields=('rok', 'mesic'), name='uniq_skladova_uzaverka_rok_mesic')],
            },
        ),
    ]
