# Generated by Django 5.2.9 on 2026-04-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0024_skladovauzaverka'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventura',
            name='stornovano_duvod',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Důvod storna'),
        ),
        migrations.AddField(
            model_name='odpisexpirace',
            name='stornovano_duvod',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Důvod storna'),
        ),
        migrations.AddField(
            model_name='prijemskladu',
            name='stornovano_duvod',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Důvod storna'),
        ),
        migrations.AddField(
            model_name='skladovauzaverka',
            name='stornovano_duvod',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Důvod storna'),
        ),
        migrations.AddField(
            model_name='vydejka',
            name='stornovano_duvod',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Důvod storna'),
        ),
    ]
