# Generated by Django 5.2.9 on 2026-04-15 14:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0025_inventura_stornovano_duvod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolozkaInventurySarze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarze', models.CharField(blank=True, default='', max_length=100, verbose_name='Šarže')),
                ('typ_data_spotreby', models.CharField(choices=[('POUZITELNOST', 'Spotřebujte do'), ('MINIMALNI_TRVANLIVOST', 'Minimální trvanlivost do'), ('NEUVADI_SE', 'Neuvádí se')], default='POUZITELNOST', max_length=30, verbose_name='Typ data spotřeby')),
                ('datum_spotreby', models.DateField(blank=True, null=True, verbose_name='Datum spotřeby')),
                ('stav_pred', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Účetní stav šarže')),
                ('fyzicky_stav', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Fyzický stav šarže')),
                ('rozdil', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Rozdíl')),
                ('cena_za_jednotku', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Cena za jednotku')),
                ('je_nova_sarze', models.BooleanField(default=False, verbose_name='Nově nalezená šarže')),
                ('poznamka', models.CharField(blank=True, default='', max_length=255, verbose_name='Poznámka')),
                ('inventura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sarze_polozky', to='sklad.inventura', verbose_name='Inventura')),
                ('sarze_skladu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventurni_polozky', to='sklad.sarzeskladu', verbose_name='Šarže skladu')),
                ('surovina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.surovina', verbose_name='Surovina')),
            ],
            options={
                'verbose_name': 'Šaržová položka inventury',
                'verbose_name_plural': 'Šaržové položky inventury',
                'ordering': ('surovina__nazev', 'datum_spotreby', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('sarze_skladu__isnull', False)), fields=('inventura', 'sarze_skladu'), name='uniq_inventura_sarze_skladu')],
            },
        ),
    ]
