# Generated by Django 5.2.9 on 2026-04-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0026_polozkainventurysarze'),
    ]

    operations = [
        migrations.AddField(
            model_name='dodavatel',
            name='datax_analytika',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='DATAx analytika'),
        ),
        migrations.AddField(
            model_name='dodavatel',
            name='datax_kod',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='DATAx kód'),
        ),
        migrations.AddField(
            model_name='dodavatel',
            name='datax_kod2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='DATAx kód 2'),
        ),
        migrations.AddField(
            model_name='dodavatel',
            name='datax_zdroj',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='DATAx zdroj'),
        ),
        migrations.AddField(
            model_name='dodavatel',
            name='typ_subjektu',
            field=models.CharField(choices=[('DODAVATEL', 'Dodavatel'), ('STREDISKO', 'Středisko'), ('PROVOZ', 'Provoz'), ('TECHNICKY', 'Technický záznam')], db_index=True, default='DODAVATEL', max_length=20, verbose_name='Typ subjektu'),
        ),
    ]
