# Generated by Django 5.2.9 on 2026-04-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provoz_jidelny', '0001_initial'),
        ('vydej', '0006_alter_stornovaneobjednavky_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NastaveniVydaje',
            fields=[
            ],
            options={
                'verbose_name': 'Nastavení výdeje',
                'verbose_name_plural': 'Nastavení výdeje',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vydej.vydejsettings',),
        ),
        migrations.CreateModel(
            name='ProvozniDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Provozní dashboard',
                'verbose_name_plural': 'Provozní dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vydej.vydejsettings',),
        ),
    ]
