# Generated by Django 5.2.9 on 2026-01-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('jidelnicek', '0003_remove_jidelnicek_jidla_polozkajidelnicku_druh_jidla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='druhjidla',
            name='viditelne_pro_skupiny',
            field=models.ManyToManyField(blank=True, help_text='Pokud není vyplněno, druh je viditelný pro všechny skupiny.', to='auth.group', verbose_name='Viditelné pro skupiny'),
        ),
    ]
