# Generated by Django 5.2.9 on 2026-01-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jidelnicek', '0004_druhjidla_viditelne_pro_skupiny'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='druhjidla',
            name='viditelne_pro_skupiny',
        ),
    ]
