# Generated by Django 5.2.9 on 2026-01-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jidelnicek', '0006_druhjidla_viditelne_pro_skupiny'),
    ]

    operations = [
        migrations.AddField(
            model_name='jidlo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='jidla/', verbose_name='Fotka jídla'),
        ),
    ]
