# Generated by Django 5.2.9 on 2026-04-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jidelnicek', '0007_jidlo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='jidlo',
            name='sk_bezmasy_pokrm',
            field=models.BooleanField(default=False, verbose_name='Spotřební koš: bezmasý pokrm'),
        ),
        migrations.AddField(
            model_name='jidlo',
            name='sk_bile_maso',
            field=models.BooleanField(default=False, verbose_name='Spotřební koš: bílé maso'),
        ),
        migrations.AddField(
            model_name='jidlo',
            name='sk_cervene_maso',
            field=models.BooleanField(default=False, verbose_name='Spotřební koš: červené maso'),
        ),
        migrations.AddField(
            model_name='jidlo',
            name='sk_dezert_s_volnym_cukrem',
            field=models.BooleanField(default=False, verbose_name='Spotřební koš: dezert s volným cukrem'),
        ),
        migrations.AddField(
            model_name='jidlo',
            name='sk_jemne_pecivo',
            field=models.BooleanField(default=False, verbose_name='Spotřební koš: jemné pečivo'),
        ),
        migrations.AddField(
            model_name='jidlo',
            name='sk_rybi_pokrm',
            field=models.BooleanField(default=False, verbose_name='Spotřební koš: rybí pokrm'),
        ),
        migrations.AddField(
            model_name='jidlo',
            name='sk_sladky_pokrm',
            field=models.BooleanField(default=False, verbose_name='Spotřební koš: sladký pokrm'),
        ),
        migrations.AddField(
            model_name='jidlo',
            name='sk_slazeny_napoj',
            field=models.BooleanField(default=False, verbose_name='Spotřební koš: nápoj s volným cukrem'),
        ),
    ]
