# Generated by Django 5.2.9 on 2026-04-20 10:46

from django.db import migrations, models


def nastav_vychozi_poradi_druhu_jidel(apps, schema_editor):
    DruhJidla = apps.get_model('jidelnicek', 'DruhJidla')

    poradi_podle_nazvu = {
        'polévka': 10,
        'polevka': 10,
        'hlavní chod': 20,
        'hlavni chod': 20,
        'oběd': 20,
        'obed': 20,
        'dezert': 30,
        'snídaně 1': 40,
        'snidane 1': 40,
        'snídaně 2': 41,
        'snidane 2': 41,
        'snídaně': 40,
        'snidane': 40,
        'přesnídávka': 50,
        'presnidavka': 50,
        'svačina': 60,
        'svacina': 60,
        'večeře': 70,
        'vecere': 70,
        'pozdní večeře': 80,
        'pozdni vecere': 80,
        'nápoj': 90,
        'napoj': 90,
    }

    for druh in DruhJidla.objects.all():
        normalized = (druh.nazev or '').strip().lower()
        druh.poradi = poradi_podle_nazvu.get(normalized, 100)
        druh.save(update_fields=['poradi'])


class Migration(migrations.Migration):

    dependencies = [
        ('jidelnicek', '0008_jidlo_sk_bezmasy_pokrm_jidlo_sk_bile_maso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='druhjidla',
            options={'ordering': ('poradi', 'nazev'), 'verbose_name': 'Druh jídla', 'verbose_name_plural': 'Druhy jídel'},
        ),
        migrations.AddField(
            model_name='druhjidla',
            name='poradi',
            field=models.PositiveIntegerField(db_index=True, default=100, help_text='Nižší číslo se zobrazí dříve. Například 10 = polévka, 20 = hlavní chod, 30 = dezert.', verbose_name='Pořadí zobrazení'),
        ),
        migrations.RunPython(nastav_vychozi_poradi_druhu_jidel, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='polozkajidelnicku',
            options={'ordering': ('druh_jidla__poradi', 'druh_jidla__nazev', 'jidlo__nazev'), 'verbose_name': 'Položka jídelníčku', 'verbose_name_plural': 'Položky jídelníčku'},
        ),
    ]
