# Generated by Django 5.2.9 on 2026-04-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jidelnicek', '0012_menuimportrun_drop_txt_source'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jidelnicek',
            index=models.Index(fields=['platnost_od', 'platnost_do'], name='jidelnicek__platnos_6b4b34_idx'),
        ),
        migrations.AddIndex(
            model_name='jidelnicek',
            index=models.Index(fields=['platnost_do', 'platnost_od'], name='jidelnicek__platnos_8c23c2_idx'),
        ),
        migrations.AddIndex(
            model_name='polozkajidelnicku',
            index=models.Index(fields=['jidelnicek', 'druh_jidla'], name='jidelnicek__jidelni_36e823_idx'),
        ),
        migrations.AddIndex(
            model_name='polozkajidelnicku',
            index=models.Index(fields=['jidelnicek', 'jidlo'], name='jidelnicek__jidelni_36c83d_idx'),
        ),
        migrations.AddIndex(
            model_name='polozkajidelnicku',
            index=models.Index(fields=['druh_jidla', 'jidlo'], name='jidelnicek__druh_ji_1f74b3_idx'),
        ),
    ]
