# Generated by Django 5.2.9 on 2026-04-27 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jidelnicek", "0013_jidelnicek_jidelnicek__platnos_6b4b34_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JidloPhotoProposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="jidla/proposals/%Y/%m/", verbose_name="Návrh fotky")),
                ("status", models.CharField(choices=[("pending", "Čeká na schválení"), ("approved", "Schváleno"), ("rejected", "Zamítnuto"), ("applied", "Použito v jídle")], db_index=True, default="pending", max_length=20, verbose_name="Stav návrhu")),
                ("prompt", models.TextField(blank=True, verbose_name="Použitý prompt")),
                ("model_name", models.CharField(blank=True, max_length=100, verbose_name="Model")),
                ("error_message", models.TextField(blank=True, verbose_name="Chybová zpráva")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Vytvořeno")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="Schváleno / zamítnuto")),
                ("jidlo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="photo_proposals", to="jidelnicek.jidlo", verbose_name="Jídlo")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_food_photo_proposals", to=settings.AUTH_USER_MODEL, verbose_name="Zkontroloval")),
            ],
            options={
                "verbose_name": "Návrh AI fotky jídla",
                "verbose_name_plural": "Návrhy AI fotek jídel",
                "ordering": ("-created_at",),
            },
        ),
    ]
