# Generated by Django 5.2.9 on 2026-04-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_adminrolemenuvisibility_item_layers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardtask',
            options={'ordering': ('category', 'name'), 'verbose_name': 'Úloha administrace', 'verbose_name_plural': 'Úlohy administrace'},
        ),
        migrations.AlterField(
            model_name='adminviewaccess',
            name='app_labels',
            field=models.JSONField(blank=True, default=list, verbose_name='Štítky admin aplikací'),
        ),
        migrations.AlterField(
            model_name='adminviewaccess',
            name='route_prefixes',
            field=models.JSONField(blank=True, default=list, verbose_name='Prefixy adres'),
        ),
        migrations.AlterField(
            model_name='appmoduletoggle',
            name='app_labels',
            field=models.JSONField(blank=True, default=list, verbose_name='Štítky admin aplikací'),
        ),
        migrations.AlterField(
            model_name='appmoduletoggle',
            name='route_prefixes',
            field=models.JSONField(blank=True, default=list, verbose_name='Prefixy adres'),
        ),
        migrations.AlterField(
            model_name='dashboardtask',
            name='command_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Příkaz pro správu'),
        ),
        migrations.AlterField(
            model_name='dashboardtask',
            name='target_url_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Název cílové URL'),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='command_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Příkaz'),
        ),
    ]
