# Generated by Django 5.2.9 on 2026-04-20 10:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dotace', '0005_remove_skupinovenastaveni_max_pocet_jidel_per_order'),
        ('jidelnicek', '0008_jidlo_sk_bezmasy_pokrm_jidlo_sk_bile_maso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dotace',
            options={'verbose_name': 'Připsaná dotace', 'verbose_name_plural': 'Připsané dotace'},
        ),
        migrations.AlterModelOptions(
            name='dotaceprojidelniskouskupinu',
            options={'verbose_name': 'Dotace podle druhu jídla', 'verbose_name_plural': 'Dotace podle druhů jídel'},
        ),
        migrations.AddField(
            model_name='dotacnipolitika',
            name='denni_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 = bez denního limitu počtu dotovaných porcí.', verbose_name='Maximální počet dotovaných porcí za den'),
        ),
        migrations.AddField(
            model_name='dotacnipolitika',
            name='denni_limit_castka',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 Kč = bez denního finančního limitu.', max_digits=10, verbose_name='Maximální výše dotace za den'),
        ),
        migrations.AddField(
            model_name='dotacnipolitika',
            name='mesicni_limit_castka',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 Kč = bez měsíčního finančního limitu.', max_digits=10, verbose_name='Maximální výše dotace za měsíc'),
        ),
        migrations.AlterField(
            model_name='dotace',
            name='castka',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Částka'),
        ),
        migrations.AlterField(
            model_name='dotace',
            name='datum',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='dotace',
            name='politika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotace.dotacnipolitika', verbose_name='Dotační politika'),
        ),
        migrations.AlterField(
            model_name='dotace',
            name='uzivatel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dotace', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel'),
        ),
        migrations.AlterField(
            model_name='dotaceprojidelniskouskupinu',
            name='castka',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volitelný přepis výchozí pevné částky pro tento druh jídla.', max_digits=8, null=True, verbose_name='Pevná částka dotace'),
        ),
        migrations.AlterField(
            model_name='dotaceprojidelniskouskupinu',
            name='dotacni_politika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dotace_skupiny', to='dotace.dotacnipolitika', verbose_name='Dotační politika'),
        ),
        migrations.AlterField(
            model_name='dotaceprojidelniskouskupinu',
            name='jidelniskova_skupina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jidelnicek.druhjidla', verbose_name='Druh jídla'),
        ),
        migrations.AlterField(
            model_name='dotaceprojidelniskouskupinu',
            name='procento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volitelný přepis výchozího procenta pro tento druh jídla.', max_digits=5, null=True, verbose_name='Procento dotace'),
        ),
        migrations.AlterField(
            model_name='dotacnipolitika',
            name='castka',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pevná sleva v Kč na jednu porci. Hodnota 0 znamená bez pevné částky.', max_digits=8, verbose_name='Výchozí pevná částka dotace'),
        ),
        migrations.AlterField(
            model_name='dotacnipolitika',
            name='mesicni_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 = bez měsíčního limitu počtu dotovaných porcí.', verbose_name='Maximální počet dotovaných porcí za měsíc'),
        ),
        migrations.AlterField(
            model_name='dotacnipolitika',
            name='procento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Procentní sleva z ceníkové ceny. Hodnota 0 znamená bez procentní dotace.', max_digits=5, verbose_name='Výchozí procento dotace'),
        ),
        migrations.AlterField(
            model_name='dotacnipolitika',
            name='skupina',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dotacni_politika', to='auth.group', verbose_name='Skupina strávníků'),
        ),
        migrations.AlterField(
            model_name='skupinovenastaveni',
            name='cerpani_debit',
            field=models.BooleanField(default=False, help_text='Skupina může čerpat konto do povoleného debetu.', verbose_name='Povolit čerpání do mínusu'),
        ),
        migrations.AlterField(
            model_name='skupinovenastaveni',
            name='debit_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximální povolený debet (v mínusu) na kontě při povoleném čerpání debetu. Např. -1500 znamená možnost čerpat až do -1500 Kč.', max_digits=8, verbose_name='Limit debetu'),
        ),
        migrations.AlterField(
            model_name='skupinovenastaveni',
            name='nutnost_dobit',
            field=models.BooleanField(default=False, help_text='Skupina musí mít před čerpáním dostatek peněz na kontě.', verbose_name='Vyžadovat kladný zůstatek'),
        ),
        migrations.AlterField(
            model_name='skupinovenastaveni',
            name='skupina',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nastaveni', to='auth.group', verbose_name='Skupina strávníků'),
        ),
    ]
