# Generated by Django 5.2.9 on 2026-04-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotace', '0006_alter_dotace_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotaceprojidelniskouskupinu',
            name='denni_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Volitelný limit dotovaných porcí pro tento druh jídla. Prázdné pole použije obecný limit z dotační politiky, 0 znamená bez limitu.', null=True, verbose_name='Maximální počet za den'),
        ),
        migrations.AddField(
            model_name='dotaceprojidelniskouskupinu',
            name='mesicni_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Volitelný měsíční limit dotovaných porcí pro tento druh jídla. Prázdné pole použije obecný limit z dotační politiky, 0 znamená bez limitu.', null=True, verbose_name='Maximální počet za měsíc'),
        ),
    ]
