# Generated by Django 5.2.9 on 2026-04-19 17:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FakturacniDavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.PositiveIntegerField(verbose_name='Rok')),
                ('mesic', models.PositiveSmallIntegerField(verbose_name='Měsíc')),
                ('datum_od', models.DateField(verbose_name='Od')),
                ('datum_do', models.DateField(verbose_name='Do')),
                ('stav', models.CharField(choices=[('NAVRH', 'Návrh'), ('UZAVRENO', 'Uzavřeno')], default='NAVRH', max_length=20, verbose_name='Stav')),
                ('vytvoreno', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vytvořeno')),
                ('dotace_celkem', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Dotace celkem')),
                ('srazky_celkem', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Srážky celkem')),
                ('polozek', models.PositiveIntegerField(default=0, verbose_name='Počet položek')),
                ('poznamka', models.TextField(blank=True, default='', verbose_name='Poznámka')),
                ('vytvoril', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fakturacni_davky', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
            ],
            options={
                'verbose_name': 'Fakturační dávka',
                'verbose_name_plural': 'Fakturační dávky',
                'ordering': ('-rok', '-mesic', '-id'),
                'unique_together': {('rok', 'mesic')},
            },
        ),
        migrations.CreateModel(
            name='FakturacniNastaveni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(default='Výchozí nastavení', max_length=80)),
                ('zahrnout_nevyzvednute', models.BooleanField(default=True, help_text='Pokud je zapnuto, do srážek ze mzdy se počítají i nevyzvednuté objednávky.', verbose_name='Zahrnout nevyzvednuté objednávky')),
                ('fakturovat_dotace', models.BooleanField(default=True, verbose_name='Fakturovat dotace')),
                ('zamestnanecke_skupiny', models.ManyToManyField(blank=True, related_name='fakturacni_nastaveni_zamestnanci', to='auth.group', verbose_name='Skupiny zaměstnanců pro srážku ze mzdy')),
            ],
            options={
                'verbose_name': 'Nastavení fakturace',
                'verbose_name_plural': 'Nastavení fakturace',
            },
        ),
        migrations.CreateModel(
            name='FakturacniPolozka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('DOTACE', 'Dotace'), ('SRAZKA', 'Srážka ze mzdy')], db_index=True, max_length=20, verbose_name='Typ')),
                ('username_snapshot', models.CharField(blank=True, default='', max_length=150, verbose_name='Login')),
                ('jmeno_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='Jméno')),
                ('osobni_cislo_snapshot', models.CharField(blank=True, default='', max_length=100, verbose_name='Osobní číslo')),
                ('skupina_snapshot', models.CharField(blank=True, default='', max_length=150, verbose_name='Skupina')),
                ('pocet_porci', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Počet porcí')),
                ('castka', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Částka')),
                ('detail', models.TextField(blank=True, default='', verbose_name='Detail')),
                ('davka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='fakturace.fakturacnidavka')),
                ('uzivatel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fakturacni_polozky', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Fakturační položka',
                'verbose_name_plural': 'Fakturační položky',
                'ordering': ('typ', 'skupina_snapshot', 'jmeno_snapshot', 'username_snapshot'),
            },
        ),
    ]
