# Generated by Django 5.2.9 on 2026-03-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrepoctyDummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(default='Přepočet', max_length=50)),
            ],
            options={
                'verbose_name': 'Přepočet',
                'verbose_name_plural': 'Přepočty',
            },
        ),
    ]
