# Generated by Django 5.2.9 on 2026-03-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepocty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prepoctydummy',
            options={'managed': False, 'verbose_name': 'Přepočet', 'verbose_name_plural': 'Přepočty'},
        ),
    ]
