# Generated by Django 5.2.9 on 2026-01-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportdummy',
            options={'managed': False, 'verbose_name': 'Reporty', 'verbose_name_plural': 'Reporty'},
        ),
    ]
