; støedník na zaèátku øádku uvozuje komentáø

; Nastavení proxy serveru
[Proxy]

; Poøádnì ani nevím k èemu tohle je, ale radši to necháme zapnutý
;BasicAuthentication=1

; Název nebo IP adresa proxy serveru
;Server=192.168.0.1

; Èíslo portu
;Port=8080

; Uživatelské jméno pro pøihlášení k serveru
;Username=popletena Marie

; Uživatelské jméno pro pøihlášení k serveru
;Password=karlicka

; Nastavení programu iKuch.exe a iKuchr.exe (residentní)
; Každý parametru zde zapsaný (èi nezapsaný) lze nahradit jeho ekvivalentem
; pøi volání z pøíkazové øádky, napø:
;   iKuch.exe -jidelna:cakovice -heslo:hovínko
;
; více informací o volání z pøíkazové øádky v readme.txt
[iKuch]

; URL adresa na které bìží komunikaèní modul dané jídelny
url=http://www.ikuch.cz/com/

; Identifikaèní øetìzec jídelny
;jidelna=cakovice

; Heslo pro pøístup k jídelnì
;heslo=abcd1234

; Vstupní soubor
; (doporuèuji používat -input:iKuchIn.txt v pøíkazové øádce,
; zamezí se tak zbyteènému posílání starých souborù u akcí,
; které nevyžadují vstup)
input=1.txt

; Výstupní soubor
output=2.txt

; Komprimovaný pøenos
; (zatím funguje jen u akcí které nevyžadují vstup,
; u ostatních ZPÙSOBUJE KRACH)
;zip=1

