[Main]
FONT_NAME=Courier New
FONT_COMPRESSED_SIZE=7
FONT_ELITE_SIZE=9
FONT_PICA_SIZE=12
MARGIN_PERCENT=100
DRAW_SPACES=0
NORMAL_CHARSET=255
SPECIAL_CHARSET=2
REPLACE_AFTER_SPECIAL=1
SpecialChars=#1,#2,#3
[Printer]
Name=HP LaserJet 1020
[Replace]
//usmìvavej
#1=#74
//neutrální
#2=#75
//zamraèenej
#3=#76
//paragraf
#21=#245
