# Generated by Django 5.2.9 on 2026-01-25 08:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_settings', '0012_operatingdays_operatingexceptions_and_more'),
        ('jidelnicek', '0005_remove_druhjidla_viditelne_pro_skupiny'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderclosingtime',
            name='cancel_until_time',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Do tohoto času lze po uzavření objednávek ještě zrušit, ale už ne znovu objednat.', verbose_name='Čas povoleného zrušení po uzavření objednávek'),
        ),
        migrations.AddField(
            model_name='orderclosingtime',
            name='druh_jidla',
            field=models.ForeignKey(blank=True, help_text='Pokud není vyplněno, nastavení platí globálně pro všechny druhy.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_closing_times', to='jidelnicek.druhjidla', verbose_name='Druh jídla'),
        ),
    ]
