# Generated by Django 5.2.9 on 2026-01-25 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_settings', '0013_orderclosingtime_cancel_until_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderclosingtime',
            name='cancel_days',
            field=models.PositiveIntegerField(default=0, help_text='Např. 0 = rušení ve stejný provozní den do stanoveného času.', verbose_name='Počet provozních dní dopředu pro zrušení'),
        ),
        migrations.AlterField(
            model_name='orderclosingtime',
            name='advance_days',
            field=models.PositiveIntegerField(default=1, help_text='Např. 3 = objednávat lze nejpozději 3 provozní dny předem do stanoveného času.', verbose_name='Počet provozních dní dopředu pro objednání'),
        ),
        migrations.AlterField(
            model_name='orderclosingtime',
            name='cancel_until_time',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Do tohoto času lze objednávku zrušit dle nastaveného počtu dní dopředu.', verbose_name='Čas povoleného zrušení objednávky'),
        ),
    ]
