# Generated by Django 5.2.9 on 2026-04-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_settings', '0014_orderclosingtime_cancel_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canteencontact',
            options={'verbose_name': 'Kontakt jídelny', 'verbose_name_plural': 'Kontakty jídelny'},
        ),
    ]
