# Generated by Django 5.2.9 on 2026-03-10 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jidelnicek', '0007_jidlo_foto'),
        ('sklad', '0011_normaspotrebnihokose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DPHSkupina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50)),
                ('sazba', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name': 'DPH skupina',
                'verbose_name_plural': 'DPH skupiny',
            },
        ),
        migrations.CreateModel(
            name='PLUKategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Kategorie PLU',
                'verbose_name_plural': 'Kategorie PLU',
            },
        ),
        migrations.CreateModel(
            name='Pokladna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50)),
                ('popis', models.CharField(blank=True, max_length=200)),
                ('aktivni', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pokladna',
                'verbose_name_plural': 'Pokladny',
            },
        ),
        migrations.CreateModel(
            name='PLUPolozka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=8)),
                ('aktivni', models.BooleanField(default=True)),
                ('dph_skupina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokladna.dphskupina')),
                ('jidlo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jidelnicek.jidlo')),
                ('kategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokladna.plukategorie')),
                ('surovina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklad.surovina')),
            ],
            options={
                'verbose_name': 'PLU položka',
                'verbose_name_plural': 'PLU položky',
            },
        ),
        migrations.CreateModel(
            name='PokladniDoklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('celkem_bez_dph', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('celkem_dph', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('celkem_s_dph', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('obsluha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokladni_doklady_obsluha', to=settings.AUTH_USER_MODEL)),
                ('pokladna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokladna.pokladna')),
                ('zakaznik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokladni_doklady_zakaznik', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pokladní doklad',
                'verbose_name_plural': 'Pokladní doklady',
            },
        ),
        migrations.CreateModel(
            name='PokladniPolozka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi', models.DecimalField(decimal_places=3, default=1, max_digits=8)),
                ('cena_jednotkova', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dph_sazba', models.DecimalField(decimal_places=2, max_digits=4)),
                ('zaklad_dph', models.DecimalField(decimal_places=2, max_digits=10)),
                ('castka_dph', models.DecimalField(decimal_places=2, max_digits=10)),
                ('castka_celkem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='pokladna.pokladnidoklad')),
                ('plu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokladna.plupolozka')),
            ],
            options={
                'verbose_name': 'Pokladní položka',
                'verbose_name_plural': 'Pokladní položky',
            },
        ),
    ]
