# Generated by Django 5.2.9 on 2026-03-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokladna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plupolozka',
            name='typ',
            field=models.CharField(choices=[('RE', 'Receptura (kusová)'), ('VA', 'Vážené zboží'), ('KO', 'Korunová položka')], default='RE', max_length=2),
        ),
    ]
