# Generated by Django 5.2.9 on 2026-03-11 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokladna', '0002_plupolozka_typ'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokladnaTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(blank=True, help_text='Pokud prázdné, použije se název z PLU.', max_length=100)),
                ('barva_pozadi', models.CharField(default='#0d6efd', help_text="CSS barva (např. #0d6efd nebo 'orange').", max_length=20)),
                ('barva_textu', models.CharField(default='#ffffff', help_text='CSS barva textu.', max_length=20)),
                ('font_bold', models.BooleanField(default=False)),
                ('font_size_px', models.PositiveIntegerField(default=14, help_text='Velikost názvu v px.')),
                ('font_family', models.CharField(blank=True, help_text="Např. 'Segoe UI', pokud prázdné, použije se výchozí.", max_length=100)),
                ('poradi', models.PositiveIntegerField(default=0, help_text='Řazení dlaždic na pokladně.')),
                ('aktivni', models.BooleanField(default=True, help_text='Určuje, zda se dlaždice zobrazuje na pokladně.')),
                ('plu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokladna.plupolozka', verbose_name='PLU položka')),
                ('pokladna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='pokladna.pokladna', verbose_name='Pokladna')),
            ],
            options={
                'verbose_name': 'Dlaždice pokladny',
                'verbose_name_plural': 'Dlaždice pokladny',
                'ordering': ['poradi', 'id'],
            },
        ),
    ]
