# Generated by Django 5.2.9 on 2026-03-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokladna', '0003_pokladnatile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokladnatile',
            options={'ordering': ('poradi', 'id'), 'verbose_name': 'Dlaždice pokladny', 'verbose_name_plural': 'Dlaždice pokladny'},
        ),
        migrations.AddField(
            model_name='pokladnatile',
            name='barva_pozadi_custom',
            field=models.CharField(blank=True, help_text='Volitelná vlastní barva (hex). Pokud vyplněno, má přednost.', max_length=20),
        ),
        migrations.AddField(
            model_name='pokladnatile',
            name='ikona',
            field=models.CharField(blank=True, choices=[('', 'Bez ikony'), ('fa-solid fa-mug-hot', 'Hrnek / nápoj'), ('fa-solid fa-utensils', 'Příbor / jídlo'), ('fa-solid fa-burger', 'Burger / svačina'), ('fa-solid fa-ice-cream', 'Zmrzlina / dezert'), ('fa-solid fa-bottle-water', 'Láhev / nápoj'), ('fa-solid fa-bread-slice', 'Pečivo'), ('fa-solid fa-egg', 'Vejce'), ('fa-solid fa-cheese', 'Sýr'), ('fa-solid fa-bowl-food', 'Miska')], help_text='Font Awesome ikona (volitelné).', max_length=80),
        ),
        migrations.AlterField(
            model_name='pokladnatile',
            name='barva_pozadi',
            field=models.CharField(choices=[('#54ae43', 'Zelená (brand primary)'), ('#f28f28', 'Oranžová (brand accent)'), ('#0d6efd', 'Modrá (primary)'), ('#198754', 'Zelená (success)'), ('#dc3545', 'Červená (danger)'), ('#ffc107', 'Žlutá (warning)'), ('#6c757d', 'Šedá (secondary)'), ('#ffffff', 'Bílá'), ('#000000', 'Černá')], default='#54ae43', help_text='Základní barva pozadí dlaždice.', max_length=20),
        ),
        migrations.AlterField(
            model_name='pokladnatile',
            name='barva_textu',
            field=models.CharField(choices=[('#ffffff', 'Bílá'), ('#000000', 'Černá'), ('#212529', 'Tmavě šedá')], default='#ffffff', help_text='Barva textu dlaždice.', max_length=20),
        ),
        migrations.AlterField(
            model_name='pokladnatile',
            name='font_family',
            field=models.CharField(blank=True, choices=[('', 'Výchozí (system)'), ("'Segoe UI', Tahoma, Geneva, Verdana, sans-serif", 'Segoe UI'), ('Arial, Helvetica, sans-serif', 'Arial'), ("'Times New Roman', Times, serif", 'Times New Roman'), ("'Courier New', Courier, monospace", 'Courier New')], help_text='Volitelný font názvu.', max_length=100),
        ),
        migrations.AlterField(
            model_name='pokladnatile',
            name='font_size_px',
            field=models.PositiveIntegerField(default=16, help_text='Velikost názvu v px.'),
        ),
        migrations.AlterField(
            model_name='pokladnatile',
            name='poradi',
            field=models.PositiveIntegerField(default=0, help_text='Řazení dlaždic na pokladně (vzestupně).'),
        ),
    ]
