# Generated by Django 5.2.9 on 2026-04-16 08:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokladna', '0004_alter_pokladnatile_options_and_more'),
        ('sklad', '0026_polozkainventurysarze'),
        ('users', '0006_stravovaciskupina_customuser_stravovaci_skupina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokladnidoklad',
            options={'ordering': ('-datum', '-id'), 'verbose_name': 'Pokladní doklad', 'verbose_name_plural': 'Pokladní doklady'},
        ),
        migrations.AddField(
            model_name='pokladnidoklad',
            name='cislo_dokladu',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Číslo dokladu'),
        ),
        migrations.AddField(
            model_name='pokladnidoklad',
            name='konto_pohyb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokladni_doklady', to='users.vklad', verbose_name='Pohyb konta'),
        ),
        migrations.AddField(
            model_name='pokladnidoklad',
            name='stav',
            field=models.CharField(choices=[('ROZPRACOVANO', 'Rozpracováno'), ('UZAVRENO', 'Uzavřeno'), ('STORNOVANO', 'Stornováno')], db_index=True, default='ROZPRACOVANO', max_length=20, verbose_name='Stav'),
        ),
        migrations.AddField(
            model_name='pokladnidoklad',
            name='storno_duvod',
            field=models.TextField(blank=True, default='', verbose_name='Důvod storna'),
        ),
        migrations.AddField(
            model_name='pokladnidoklad',
            name='stornoval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokladni_doklady_stornoval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pokladnidoklad',
            name='stornovano_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stornováno'),
        ),
        migrations.AddField(
            model_name='pokladnidoklad',
            name='uzavrel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokladni_doklady_uzavrel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pokladnidoklad',
            name='uzavren_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Uzavřeno'),
        ),
        migrations.AddField(
            model_name='pokladnidoklad',
            name='zpusob_platby',
            field=models.CharField(blank=True, choices=[('HOTOVOST', 'Hotovost'), ('KARTA', 'Karta'), ('KONTO', 'Konto strávníka')], default='', max_length=20, verbose_name='Způsob platby'),
        ),
        migrations.AddField(
            model_name='pokladnipolozka',
            name='jednotka_text',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Jednotka'),
        ),
        migrations.AddField(
            model_name='pokladnipolozka',
            name='nazev_snapshot',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Název při prodeji'),
        ),
        migrations.AddField(
            model_name='pokladnipolozka',
            name='skladovy_pohyb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokladni_polozky', to='sklad.pohybskladu', verbose_name='Skladový pohyb'),
        ),
        migrations.CreateModel(
            name='PokladniUzaverka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Datum')),
                ('vytvoreno_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('pocet_dokladu', models.PositiveIntegerField(default=0, verbose_name='Počet dokladů')),
                ('pocet_storen', models.PositiveIntegerField(default=0, verbose_name='Počet storen')),
                ('hotovost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Hotovost')),
                ('karta', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Karta')),
                ('konto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Konto strávníků')),
                ('storna', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Storna')),
                ('hotovost_spoctena', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Spočtená hotovost')),
                ('rozdil_hotovosti', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Rozdíl hotovosti')),
                ('poznamka', models.TextField(blank=True, default='', verbose_name='Poznámka')),
                ('pokladna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uzaverky', to='pokladna.pokladna')),
                ('uzavrel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokladni_uzaverky', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Denní uzávěrka pokladny',
                'verbose_name_plural': 'Denní uzávěrky pokladny',
                'ordering': ('-datum', '-id'),
                'unique_together': {('pokladna', 'datum')},
            },
        ),
        migrations.AddField(
            model_name='pokladnidoklad',
            name='uzaverka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doklady', to='pokladna.pokladniuzaverka', verbose_name='Denní uzávěrka'),
        ),
    ]
