# Generated by Django 5.2.9 on 2026-04-19 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokladna', '0005_alter_pokladnidoklad_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pokladna',
            name='qr_bic',
            field=models.CharField(blank=True, help_text='Volitelné. Některé banky jej u QR platby nevyžadují.', max_length=11, verbose_name='BIC/SWIFT pro QR platby'),
        ),
        migrations.AddField(
            model_name='pokladna',
            name='qr_iban',
            field=models.CharField(blank=True, help_text='Např. CZ6508000000192000145399. Bez IBAN nelze vygenerovat QR platbu.', max_length=34, verbose_name='IBAN pro QR platby'),
        ),
        migrations.AddField(
            model_name='pokladna',
            name='qr_prijemce',
            field=models.CharField(blank=True, help_text='Volitelné jméno příjemce platby.', max_length=80, verbose_name='Příjemce QR platby'),
        ),
        migrations.AddField(
            model_name='pokladna',
            name='qr_zprava',
            field=models.CharField(blank=True, default='Pokladna', max_length=60, verbose_name='Výchozí zpráva QR platby'),
        ),
        migrations.AddField(
            model_name='pokladnidoklad',
            name='qr_payload',
            field=models.TextField(blank=True, default='', verbose_name='QR platební data'),
        ),
        migrations.AddField(
            model_name='pokladnidoklad',
            name='qr_potvrdil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokladni_qr_potvrdil', to=settings.AUTH_USER_MODEL, verbose_name='QR potvrdil'),
        ),
        migrations.AddField(
            model_name='pokladnidoklad',
            name='qr_potvrzen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='QR potvrzeno'),
        ),
        migrations.AddField(
            model_name='pokladnidoklad',
            name='qr_vytvoren_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='QR vytvořeno'),
        ),
        migrations.AddField(
            model_name='pokladniuzaverka',
            name='qr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='QR platby'),
        ),
        migrations.AlterField(
            model_name='pokladnidoklad',
            name='stav',
            field=models.CharField(choices=[('ROZPRACOVANO', 'Rozpracováno'), ('CEKA_NA_QR', 'Čeká na QR platbu'), ('UZAVRENO', 'Uzavřeno'), ('STORNOVANO', 'Stornováno')], db_index=True, default='ROZPRACOVANO', max_length=20, verbose_name='Stav'),
        ),
        migrations.AlterField(
            model_name='pokladnidoklad',
            name='zpusob_platby',
            field=models.CharField(blank=True, choices=[('HOTOVOST', 'Hotovost'), ('KARTA', 'Karta'), ('KONTO', 'Konto strávníka'), ('QR', 'QR platba')], default='', max_length=20, verbose_name='Způsob platby'),
        ),
    ]
