# Generated by Django 5.2.9 on 2026-04-19 11:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokladna', '0006_pokladna_qr_bic_pokladna_qr_iban_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pokladna',
            name='hotovostni_zustatek',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Výchozí hotovost v pokladně. Používá se pro provozní přehledy a finanční reporty.', max_digits=12, verbose_name='Pokladní hotovost'),
        ),
        migrations.CreateModel(
            name='PokladniSmazanaPolozka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_snapshot', models.CharField(blank=True, default='', max_length=150, verbose_name='Název při smazání')),
                ('mnozstvi', models.DecimalField(decimal_places=3, default=1, max_digits=8)),
                ('jednotka_text', models.CharField(blank=True, default='', max_length=20, verbose_name='Jednotka')),
                ('cena_jednotkova', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('dph_sazba', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('zaklad_dph', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('castka_dph', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('castka_celkem', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('smazano_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Smazáno')),
                ('duvod', models.CharField(blank=True, default='', max_length=120, verbose_name='Důvod')),
                ('doklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smazane_polozky', to='pokladna.pokladnidoklad')),
                ('plu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pokladna.plupolozka')),
                ('smazal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokladni_smazane_polozky', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Smazaná pokladní položka',
                'verbose_name_plural': 'Smazané pokladní položky',
                'ordering': ('-smazano_at', '-id'),
            },
        ),
    ]
